#!/usr/bin/env python3
"""Classify every function from its profile, and emit the annotated map.

    tools/ghidra/classify.py PROFILE.json > docs/audit/function_map.md

This is BULK naming by SIGNATURE, not by reading. Every row says which
evidence produced it, because a signature-derived label is a hypothesis
and a hand-read one is not (docs/log/LOOP-DECOMPILE.md 50). Rows marked
READ were read to their return; rows marked by a signature were not.

The signatures come from routines that WERE read, so each one is grounded
even though its application is mechanical:
  $21/$22/$24  animation frame index, timer, script    [32]
  $0C/$10 + $14/$1A  16.16 position and velocity       [29]
  $34-$3A / $54-$5A / $60-$66  the three hitboxes      [34][45]
  $02          the routine pointer the dispatcher calls [28]
  $3E/$3C      the object claim locks                   [38]
  $2F          priority band                            [34]
  calls 0x3F04 hide this object's sprite                [30]
  calls 0x3DD8/0x3D14  world-to-screen and cull         [33]
  calls 0x3352 enqueue a sound command                  [32]
  calls 0x3B2E/0x3BCE  palette request/release          [2]
  calls 0xD8BA/0xD99C  collision / floor test           [34][35]
"""
import json
import sys

READ = {
 0x2AAC:'irq4_handler', 0x2DBC:'palette_queue_drain', 0x2E74:'input_edges',
 0x30B2:'colour_cycle_streamer', 0x3108:'sky_palette_gradient',
 0x3352:'sound_enqueue', 0x369C:'clear_textram', 0x36B0:'clear_tileram',
 0x36C4:'clear_spriteram_and_pool', 0x397E:'wait_frame_flag',
 0x3838:'sky_palette_flat', 0x3952:'set_level_palettes', 0x398E:'object_dispatcher',
 0x3A9A:'textram_stride_write', 0x3B2E:'request_palette_update',
 0x3B6C:'allocate_palette_slot', 0x3BCE:'release_palette_slot',
 0x3BEC:'build_palette_upload_queue', 0x3C84:'sprite_frame_lookup',
 0x3CA6:'order_list_insert', 0x3CD4:'zoom_scale_lookup',
 0x3D14:'sprite_build_depth_banded', 0x3DD8:'sprite_build_and_cull',
 0x3F04:'hide_object_sprite', 0x3F20:'integrate_position',
 0x3F40:'clamp_x_velocity', 0x3F72:'clamp_y_velocity', 0x3FBE:'rng_next',
 0x1694:'unpack_level_tilemap', 0x16BE:'tilemap_unpack_hi',
 0x16DE:'tilemap_unpack_lo', 0x170A:'tilemap_block_04', 0x174E:'tilemap_block_a5',
 0x65AA:'restore_position', 0x65CA:'animate_variant', 0x669C:'animate',
 0x6654:'animation_peek_next', 0x674E:'animation_frame_fetch',
 0xD47E:'hitbox_a_expand', 0xD4B8:'hitbox_b_expand', 0xD4F2:'hitbox_c_expand',
 0xD5A6:'walk_player_slots', 0xD8BA:'collide_box_b', 0xD99C:'floor_collide',
 0x5BE:'test_mode_screen', 0xE1E8:'tick_kill_counters',
}
SIG = [
 ('collision',   lambda f,c: {'0xD8BA','0xD99C'} & c or {'0x34','0x38','0x54','0x58','0x60'} & f),
 ('animation',   lambda f,c: {'0x21','0x22','0x24'} <= f or {'0x669C','0x65CA','0x674E'} & c),
 ('claim/lock',  lambda f,c: {'0x3E','0x3C'} & f),
 ('draws',       lambda f,c: {'0x3DD8','0x3D14','0x3CA6'} & c),
 ('despawns',    lambda f,c: '0x3F04' in c),
 ('motion',      lambda f,c: {'0x14','0x1A'} & f or {'0x3F20','0x3F40','0x3F72'} & c),
 ('state change',lambda f,c: '0x02' in f),
 ('palette',     lambda f,c: {'0x3B2E','0x3BCE','0x3B6C'} & c or {'0x0A','0x0B'} & f),
 ('sound',       lambda f,c: '0x3352' in c),
]

def main():
    fns = json.load(open(sys.argv[1]))['functions']
    print('# Altered Beast: annotated function map\n')
    print('Generated by `tools/ghidra/classify.py` from '
          '`tools/ghidra/func_profile.py` output, against the seeded and')
    print('bounds-repaired project (`tools/ghidra/rebuild.sh`, then '
          '`fix_bounds.py`). %d functions.\n' % len(fns))
    print('**READ** = read to its return and verified. Everything else is a '
          'SIGNATURE match:')
    print('a hypothesis from which object fields and callees it touches, not '
          'a reading.\n')
    print('| entry | size | callers | class | fields | evidence |')
    print('|---|---|---|---|---|---|')
    counts = {}
    for f in sorted(fns, key=lambda x: int(x['entry'], 16)):
        ep = int(f['entry'], 16)
        fl = set(f['obj_fields']); ce = set(f['callees'])
        if ep in READ:
            cls, ev = READ[ep], 'READ'
        else:
            hits = [n for n, t in SIG if t(fl, ce)]
            cls = ' + '.join(hits) if hits else (
                  'hardware' if f['regions'] else 'leaf/helper')
            ev = 'signature'
        counts[cls.split(' + ')[0]] = counts.get(cls.split(' + ')[0], 0) + 1
        print('| 0x%05X | %d | %d | %s | %s | %s |'
              % (ep, f['size'], f['callers'], cls,
                 ' '.join(sorted(fl)[:6]) or '-', ev))
    print('\n## Class totals\n')
    for k in sorted(counts, key=lambda x: -counts[x]):
        print('- %s: %d' % (k, counts[k]))

if __name__ == '__main__':
    main()
