#!/usr/bin/env python3
"""Render the video-surface inventory as markdown.

    tools/ghidra_run.sh script video_map.py OUT.json
    tools/ghidra/video_map_md.py OUT.json > docs/audit/video_map.md

NAMES are only attached where this thread verified the routine against
our own bytes AND, where the entry says so, a running frame. Everything
else is listed unnamed on purpose: an address is not a meaning
(HANDOFF-DECOMPILE, the verification rule).
"""
import json
import sys

# entry -> (name, the LOOP-DECOMPILE entry that justifies it)
VERIFIED = {
    0x016BE: ('tilemap_unpack_hi', 10),
    0x016DE: ('tilemap_unpack_lo', 10),
    0x0170A: ('tilemap_block_04', 10),
    0x0174E: ('tilemap_block_a5', 10),
    0x02AAC: ('irq4_handler (sprite upload at 0x2B16, scroll regs at 0x2AD2)', 13),
    0x03952: ('set_level_palettes', 3),
    0x0369C: ('clear_textram', 13),
    0x036B0: ('clear_tileram', 13),
    0x036C4: ('clear_spriteram_and_pool', 13),
    0x0397E: ('wait_frame_flag', 2),
    0x03B2E: ('request_palette_update', 2),
    0x03B6C: ('allocate_palette_slot', 2),
    0x03BCE: ('release_palette_slot', 2),
    0x03BEC: ('build_palette_upload_queue', 3),
}

ORDER = ['spriteram', 'tileram', 'textram', 'palette', 'io', 'mcu_mailbox',
         'frameflag', 'tilebank']


def main():
    with open(sys.argv[1]) as fh:
        fns = json.load(fh)['functions']
    total = sum(f['size'] for f in fns)
    named = [f for f in fns if int(f['entry'], 16) in VERIFIED]

    print('# The Altered Beast video surface')
    print()
    print('Generated by `tools/ghidra/video_map.py` + `tools/ghidra/video_map_md.py`')
    print('against the seeded project (`tools/ghidra/rebuild.sh`). Addresses are')
    print('the ARCADE map. Regenerate rather than edit.')
    print()
    print('%d of the program\'s functions touch System 16B video, palette, sprite'
          % len(fns))
    print('or IO hardware: %d bytes, %.1f%% of the 262144-byte rom. %d of them carry'
          % (total, 100.0 * total / 262144, len(named)))
    print('a name this thread verified; the rest are listed unnamed on purpose.')
    print()
    print('| entry | size | regions | callers | name |')
    print('|---|---|---|---|---|')
    for f in fns:
        ep = int(f['entry'], 16)
        regs = ' '.join('%s:%d' % (r, f['regions'][r])
                        for r in ORDER if r in f['regions'])
        nm = VERIFIED.get(ep)
        label = '`%s` (LOOP-DECOMPILE %d)' % nm if nm else ''
        print('| 0x%05X | %d | %s | %d | %s |'
              % (ep, f['size'], regs, len(f['callers']), label))
    print()
    print('## Where each region is reached from')
    print()
    for r in ORDER:
        hits = [f for f in fns if r in f['regions']]
        if not hits:
            continue
        n = sum(f['regions'][r] for f in hits)
        print('- **%s** — %d accesses across %d functions.' % (r, n, len(hits)))
    print()
    print('An access counted here is an instruction whose operand names a')
    print('hardware address in either form: an absolute operand, or an immediate')
    print('loaded into a register. Counting only the first form hides most of')
    print('this program (docs/log/LOOP-DECOMPILE.md 20).')


if __name__ == '__main__':
    main()
