/* AUTO-GENERATED by tools/speech_bake.py — do not edit.
 * IMA ADPCM @ 16000 Hz, even sample = LOW nibble. */
#ifndef SPEECH_BANK_H
#define SPEECH_BANK_H

#include <stdint.h>

struct speech_sample { const uint8_t *data; uint32_t nibbles; };
#define SPEECH_BANK_COUNT 29
extern const struct speech_sample speech_bank[SPEECH_BANK_COUNT];

#endif
