/* generated by tools/bake_cat1vis.py — 1 = this cat1 tile
 * is VISIBLE and must be composed; 0 = occluded by a fully
 * opaque foreground tile and never reached by the mixer
 * (jts16_prio.v:83-95). Same geometry as cat1map.bin. */
#define CAT1VIS_BYTES_PER_SCENE 2560
static const unsigned short cat1vis_counts[5] = { 2080, 8594, 6133, 1119, 3133 };
