/* generated by tools/bake_cat1map.py — per-scene tile
 * priority (CAT1) bitmaps. One bit per tile, MSB first:
 * scene s tile n = cat1map[s*2560 + (n>>3)] & (0x80>>(n&7)).
 * Static per scene; see docs/log/LOOP-DECOMPILE.md 31. */
#define CAT1_SCENES 5
#define CAT1_TILES 20480
#define CAT1_BYTES_PER_SCENE 2560
static const unsigned short cat1_counts[CAT1_SCENES] = { 2312, 8960, 7360, 1280, 3520 };
