/* GENERATED by tools/glow_bake.py — do not edit.
 * Level-1 glow animators derived from capture; the
 * SH-2 (GLOW_ANIM) plays them at 60Hz vint — the
 * arcade's own rate. Regenerate per round. */
#define GLOW_RAMP0 0x99   /* 7 words, rotate -2/tick */
#define GLOW_WAVE_N 6
static const uint16_t glow_wave[GLOW_WAVE_N][5]
    __attribute__((section(".palscenes"))) = {
    { 0x100F, 0x100F, 0x100F, 0x100F, 0x100F },
    { 0x305F, 0x100F, 0x100F, 0x100F, 0x100F },
    { 0x307F, 0x305F, 0x100F, 0x100F, 0x100F },
    { 0x309F, 0x307F, 0x305F, 0x100F, 0x100F },
    { 0x30BF, 0x309F, 0x307F, 0x305F, 0x100F },
    { 0x30DF, 0x30BF, 0x309F, 0x307F, 0x305F },
};
static const uint8_t glow_dwell[GLOW_WAVE_N]
    __attribute__((section(".palscenes"))) = { 4, 2, 2, 2, 2, 4 };
/* doubled ring: word j at phase p = glow_ring2[p+j] — no runtime %7 (SDRAM-code diet) */
static const uint16_t glow_ring2[14]
    __attribute__((section(".palscenes"))) = { 0x4900, 0x4A00, 0x4B00, 0x4C00, 0x4D00, 0x4E00, 0x4F00, 0x4900, 0x4A00, 0x4B00, 0x4C00, 0x4D00, 0x4E00, 0x4F00 };
