#include "mars.h"

/* Chunky 8bpp altbeast tiles: 16384 tiles x 64 bytes, pens 0-7.
 * Generated by tools/gen_tiles.py, embedded via tiles_data.s. */
extern const uint8_t altbeast_tiles[];

#define TILE_COLS   40
#define TILE_ROWS   28

/* Draw one 8x8 chunky tile at tile-grid position (tx, ty) with a
 * palette base added to every nonzero pen. Framebuffer is 8bpp with
 * 320-byte lines; byte writes to SDRAM framebuffer are unreliable on
 * real hardware, so pack two pixels per 16-bit word write. */
static void draw_tile(volatile uint16_t *fb, int tx, int ty,
                      const uint8_t *tile, uint8_t palbase)
{
    volatile uint16_t *dst = fb + 0x100 + (ty * 8) * 160 + tx * 4;
    for (int y = 0; y < 8; y++) {
        for (int xw = 0; xw < 4; xw++) {
            uint8_t p0 = tile[xw * 2];
            uint8_t p1 = tile[xw * 2 + 1];
            if (p0) p0 += palbase;
            if (p1) p1 += palbase;
            dst[xw] = ((uint16_t)p0 << 8) | p1;
        }
        tile += 8;
        dst += 160;
    }
}

static void draw_screen(void)
{
    volatile uint16_t *fb = &MARS_FRAMEBUFFER;

    for (int ty = 0; ty < TILE_ROWS; ty++) {
        /* Sample two regions of the tile ROM: the font/UI bank at the
         * top of the sheet, then terrain art further in. */
        int base = (ty < 14) ? 0 : 4096;
        int row = (ty < 14) ? ty : ty - 14;
        for (int tx = 0; tx < TILE_COLS; tx++) {
            int tn = base + row * TILE_COLS + tx;
            draw_tile(fb, tx, ty, &altbeast_tiles[tn * 64],
                      (ty < 14) ? 0 : 8);
        }
    }
}

void m_main(void)
{
    /* Release the secondary SH-2 from its S_OK wait (crt0 fix — see
     * 32x-builder DEVLOG). Must happen before anything else. */
    MARS_SYS_COMM4 = 0;

    Hw32xInit(MARS_VDP_MODE_256, 0);

    /* Pens 1-7: gray ramp. Pens 9-15: amber ramp (palbase 8). */
    volatile uint16_t *cram = &MARS_CRAM;
    cram[0] = COLOR(0, 0, 0);
    for (int i = 1; i < 8; i++)
        cram[i] = COLOR(i * 4, i * 4, i * 4);
    cram[8] = COLOR(0, 0, 0);
    for (int i = 1; i < 8; i++)
        cram[8 + i] = COLOR(i * 4, i * 3, i);

    /* Draw into both framebuffers so the image is stable. */
    draw_screen();
    Hw32xScreenFlip(1);
    draw_screen();
    Hw32xScreenFlip(1);

    for (;;)
        ;
}
