/* GENERATED by tools/bake_mdspr.py -- do not edit. */
#define MDSPR_NKEYS 21
#define MDSPR_TILE0 1024   /* VRAM 0x8000 */
#define MDSPR_NSCENES 2
typedef struct { unsigned short addr; unsigned short d2lo9;
    unsigned char bank, height, set, wpx, hpx, nsub;
    unsigned short sub0; } mdspr_key_t;
typedef struct { unsigned char dx, dy, size, pad;
    unsigned short tile; } mdspr_sub_t;
typedef struct { unsigned char key0, nkeys, anchor, aset1;
    unsigned short blob_woff, blob_words; } mdspr_scene_t;
/* anchor 0xFF = dynamic between the scene's two sets
 * (aset1 = the alternate; key0's set = the initial) */
static const mdspr_key_t mdspr_keys[MDSPR_NKEYS] = {
  { 0x6212, 0x007, 3, 57, 0x09, 26, 57, 2, 0 },  /* 3_6212_0007_039 x1522 */
  { 0x6051, 0x008, 3, 56, 0x09, 30, 56, 2, 2 },  /* 3_6051_0008_038 x1210 */
  { 0x63A1, 0x007, 3, 58, 0x09, 25, 58, 2, 4 },  /* 3_63A1_0007_03A x1110 */
  { 0x6051, 0x008, 3, 37, 0x09, 24, 37, 2, 6 },  /* 3_6051_0008_025 x906 */
  { 0x6DF9, 0x00C, 3, 36, 0x09, 47, 36, 4, 8 },  /* 3_6DF9_000C_024 x93 */
  { 0x6FA6, 0x00F, 3, 20, 0x09, 58, 20, 2, 12 },  /* 3_6FA6_000F_014 x72 */
  { 0x6058, 0x108, 3, 56, 0x09, 30, 56, 2, 14 },  /* 3_6058_0108_038 x57 */
  { 0x6C3D, 0x008, 3, 56, 0x09, 31, 56, 2, 16 },  /* 3_6C3D_0008_038 x48 */
  { 0xFCBD, 0x111, 2, 32, 0xFF, 66, 32, 3, 18 },  /* 2_FCBD_FFFF_032 x20 */
  { 0xFBAE, 0x003, 2, 15, 0xFF, 10, 15, 1, 21 },  /* 2_FBAE_FFFF_015 x5 */
  { 0xFBB0, 0x103, 2, 15, 0xFF, 10, 15, 1, 22 },  /* 2_FBB0_FFFF_015 x5 */
  { 0xFCBD, 0x111, 2, 48, 0xFF, 66, 48, 6, 23 },  /* 2_FCBD_FFFF_048 x5 */
  { 0xFDCD, 0x111, 2, 16, 0xFF, 66, 16, 3, 29 },  /* 2_FDCD_FFFF_016 x5 */
  { 0xFCAD, 0x011, 2, 32, 0xFF, 66, 32, 3, 32 },  /* 2_FCAD_FFFF_032 x4 */
  { 0xFBD1, 0x00E, 2, 16, 0xFF, 48, 16, 2, 35 },  /* 2_FBD1_FFFF_016 x3 */
  { 0xF8E6, 0x00D, 2, 54, 0xFF, 51, 54, 4, 37 },  /* 2_F8E6_FFFF_054 x2 */
  { 0xCAA3, 0x011, 2, 29, 0xFF, 64, 29, 2, 41 },  /* 2_CAA3_FFFF_029 x2 */
  { 0x0D42, 0x009, 2, 59, 0xFF, 32, 59, 2, 43 },  /* 2_0D42_FFFF_059 x1 */
  { 0xFCAD, 0x011, 2, 48, 0xFF, 66, 48, 6, 45 },  /* 2_FCAD_FFFF_048 x1 */
  { 0xFDBD, 0x011, 2, 16, 0xFF, 66, 16, 3, 51 },  /* 2_FDBD_FFFF_016 x1 */
  { 0xF8E6, 0x00D, 2, 24, 0xFF, 51, 24, 2, 54 },  /* 2_F8E6_FFFF_024 x1 */
};
static const mdspr_sub_t mdspr_subs[56] = {
  { 0, 0, 0x0F, 0, 0 },
  { 0, 32, 0x0F, 0, 16 },
  { 0, 0, 0x0F, 0, 32 },
  { 0, 32, 0x0E, 0, 48 },
  { 0, 0, 0x0F, 0, 60 },
  { 0, 32, 0x0F, 0, 76 },
  { 0, 0, 0x0B, 0, 92 },
  { 0, 32, 0x08, 0, 104 },
  { 0, 0, 0x0F, 0, 107 },
  { 32, 0, 0x07, 0, 123 },
  { 0, 32, 0x0C, 0, 131 },
  { 32, 32, 0x04, 0, 135 },
  { 0, 0, 0x0E, 0, 137 },
  { 32, 0, 0x0E, 0, 149 },
  { 0, 0, 0x0F, 0, 161 },
  { 0, 32, 0x0E, 0, 177 },
  { 0, 0, 0x0F, 0, 189 },
  { 0, 32, 0x0E, 0, 205 },
  { 0, 0, 0x0F, 0, 0 },
  { 32, 0, 0x0F, 0, 16 },
  { 64, 0, 0x03, 0, 32 },
  { 0, 0, 0x05, 0, 36 },
  { 0, 0, 0x05, 0, 40 },
  { 0, 0, 0x0F, 0, 44 },
  { 32, 0, 0x0F, 0, 60 },
  { 64, 0, 0x03, 0, 76 },
  { 0, 32, 0x0D, 0, 80 },
  { 32, 32, 0x0D, 0, 88 },
  { 64, 32, 0x01, 0, 96 },
  { 0, 0, 0x0D, 0, 98 },
  { 32, 0, 0x0D, 0, 106 },
  { 64, 0, 0x01, 0, 114 },
  { 0, 0, 0x0F, 0, 116 },
  { 32, 0, 0x0F, 0, 132 },
  { 64, 0, 0x03, 0, 148 },
  { 0, 0, 0x0D, 0, 152 },
  { 32, 0, 0x05, 0, 160 },
  { 0, 0, 0x0F, 0, 164 },
  { 32, 0, 0x0B, 0, 180 },
  { 0, 32, 0x0E, 0, 192 },
  { 32, 32, 0x0A, 0, 204 },
  { 0, 0, 0x0F, 0, 213 },
  { 32, 0, 0x0F, 0, 229 },
  { 0, 0, 0x0F, 0, 245 },
  { 0, 32, 0x0F, 0, 261 },
  { 0, 0, 0x0F, 0, 277 },
  { 32, 0, 0x0F, 0, 293 },
  { 64, 0, 0x03, 0, 309 },
  { 0, 32, 0x0D, 0, 313 },
  { 32, 32, 0x0D, 0, 321 },
  { 64, 32, 0x01, 0, 329 },
  { 0, 0, 0x0D, 0, 331 },
  { 32, 0, 0x0D, 0, 339 },
  { 64, 0, 0x01, 0, 347 },
  { 0, 0, 0x0E, 0, 349 },
  { 32, 0, 0x0A, 0, 361 },
};
static const mdspr_scene_t mdspr_scenes[MDSPR_NSCENES] = {
  { 0, 8, 0x09, 0x00, 0, 3472 },  /* normal */
  { 8, 13, 0xFF, 0x00, 3472, 5920 },  /* boss */
};
