/* generated by tools/bake_sprites.py -- do not edit */
#ifndef SPRBAKE_H
#define SPRBAKE_H
#define SPRBAKE_MAGIC     0x5350424Bu
#define SPRBAKE_VERSION   1
#define SPRBAKE_SLOTS     4096
#define SPRBAKE_MASK      4095
#define SPRBAKE_SLOT_SZ   12
#define SPRBAKE_FRAMES    389
#define SPRBAKE_BYTES     681446
#define SPRBAKE_MAXPROBE  2
#endif
