! LOOP 17 — pre-decoded sprite frames + hash index, generated by
! tools/bake_sprites.py from the discovery CSVs in discover/.
!
! Linked ONLY under SPRBAKE=1 (the Makefile filters this object out of
! the default wildcard): the blob is ~660KB of cart ROM, and it is dead
! weight until compose_sprites has the fast path that reads it.
!
! Layout is documented in tools/bake_sprites.py and sh_src/sprbake.h.
! Pinned at cart 0x340000 by mars.ld (.sprbake): the 768KB window
! above .gamehigh — the blob budget bake_sprites.py enforces. It sat
! in .rodata (inside the ROM image) until 2026-09-01, when the boss
! frames (+80KB) blew the image's 248-byte slack under .palscenes.
        .section .sprbake, "a" 
        .align  4
        .global _sprbake_blob
_sprbake_blob:
        .incbin "sprbake.bin"
