! Altered Beast sprite data, 16-bit-BE interleave, generated by tools/gen_sprites.py
        .section .rodata
        .align  4
        .global _altbeast_sprites
_altbeast_sprites:
        .incbin "sprites.bin"
