! Baked MD 4bpp tiles, generated by tools/bake_tiles_md.py --emit.
! Index: 5 rounds x 128 u16 block numbers (0xFFFF = set not baked),
! then 4KB blocks of 64 codes x (FG,BG) x 32 bytes.
! GUARDED: SHOBJS wildcards sh_src/*.s, so without this the 425KB blob
! would link into every build. TILESMD=1 defines the symbol.
        .ifdef TILES_MD
        .section .tilesmd
        .align  4
        .global _altbeast_tiles_md
_altbeast_tiles_md:
        .incbin "tiles_md.bin"
        .endif
