/* generated by tools/bake_tiles_md.py --emit: the blob's shape,
 * shared by the SH-2 (index stride) and the 68K (slim_fetch bounds). */
#define TILESMD_SCENES 10
#define TILESMD_INDEX_BYTES 2560
#define TILESMD_BYTES 518656
