/* generated by patch_game.py for altbeast */
#define GAME_IRQ4 0x902AAC
/* target of the one abs.w jmp the rebase cannot widen (ABSW_JMP) */
#define GAME_ABSW_JMP_TARGET 0x90047E
/* i8751 mailboxes in work RAM (MCU_BUSY / MCU_COINS / MCU_SND) */
#define GAME_MCU_BUSY  0xFFF0C0
#define GAME_MCU_COINS 0xFFF0C2
#define GAME_MCU_SND   0xFFF0C4
