/* GENERATED by tools/bake_mdspr.py -- do not edit. */
#define MDSPR_BLOB_WORDS 4560  /* scene 0 (boot upload) */
#define MDSPR_VRAM_BASE 0x8000
/* cart placement is FIXED by sh_src/mars.ld (.mdsprart) */
#define MDSPR_CART_BANK 2
#define MDSPR_CART_WINOFF 0xF9100
#define MDSPR_NSCENES 2
/* per-scene blob word-offset,word-count (68K runtime
 * upload at scene cuts, chunked in the vint) */
static const unsigned short mdspr_scene_blob[2][2] = {
  { 0, 4560 },  /* normal */
  { 4560, 5920 },  /* boss */
};
