#include "common.h"
#include "game_irq.h"      /* GAME_IRQ4: generated by patch_game.py */

	.section .text.keepboot

/* poor man's debug - set bg color */
.macro SETBG _color
		move.l	#0xC0000000,(0xC00004)
		move.w	#\_color,(0xC00000)
.endm

/* set bg color and STOP */
.macro TRPBG _color
		move.l	#0xC0000000,(0xC00004)
		move.w	#\_color,(0xC00000)
	101:
		bra		101b
.endm

/* same as above but keep setting bg color */
.macro TRPBG2 _color
	101:
		move.l	#0xC0000000,(0xC00004)
		move.w	#\_color,(0xC00000)
		bra		101b
.endm


_irq_jmptab:	/* fixed 6-byte entries — trampolines at cart 0x200 index into this */
		.word	0x4EF9
		.long	_start
		.word	0x4EF9
		.long	_except
		.word	0x4EF9
		.long	_hblank
		.word	0x4EF9
		.long	_vblank

_except:
		TRPBG2	0x00E

_start:
.ifdef BOOT_HALT
		/* HARDWARE PROBE: paint the backdrop blue with our very first
		 * instructions and stop. Blue = the BIOS handed the 68K to our
		 * code; black = it never did (header / cart size / security). */
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x0800,(0xC00000).l
	9:	bra.s	9b
.endif
	;// Clear Work RAM
		moveq	#0,d0
		move.w	#0x3FFF,d1
		suba.l	a1,a1
	1:
		move.l	d0,-(a1)
		dbf		d1,1b

	;// Copy initialized variables from ROM to Work RAM.
	;// .data is linked at 0xFF0100 (0xFF0000-0xFF00FF is reserved for the
	;// game boot's mapper-mirror writes); the clear loop leaves a1=0xFF0000,
	;// so set the copy destination explicitly.
		lea		__text_end,a0
		lea		0xFF0100,a1
		move.w	#__data_size,d0
		lsr.w	#1,d0
		subq.w	#1,d0
	2:
		move.w	(a0)+,(a1)+
		dbf		d0,2b
.ifdef BOOT_STAGE
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x000E,(0xC00000).l	/* stage: RED = RAM cleared + .data copied */
.endif

	init_joypads:
		lea		IO_BASE,a0
		move.b	#0x40,0x09(a0)
		move.b	#0x40,0x0B(a0)
		move.b	#0x40,0x03(a0)
		move.b	#0x40,0x05(a0)

	init_vdp:
		lea		VDP_CTRL_PORT,a1		/* VDP cmd/sts reg */
		move.w	#0x8000,d0				/* set VDP register 0 */
		move.w	#0x0100,d2
		lea		InitVDPRegs(pc),a0
		moveq	#18,d1
	init_vdp_reg:
		move.b	(a0)+,d0				/* lower byte = register data */
		move.w	d0,(a1)					/* set VDP register */
		add.w	d2,d0					/* + 0x0100 = next register */
		dbra	d1,init_vdp_reg
.ifdef BOOT_STAGE
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x00E0,(0xC00000).l	/* stage: GREEN = VDP registers written */
.endif

		move.l	#VRAM_ADDR_CMD,(a1)		/* write VRAM address 0 */
		lea		(VDP_DATA_PORT),a2		/* VDP data reg */
		lea		font_data(pc),a0
		move.w	#45*8-1,d2
	7:
		move.l	(a0)+,d0				/* font fg mask */
		move.l	d0,d1
		not.l	d1						/* font bg mask */
		andi.l	#0x11111111,d0			/* set font fg color */
		andi.l	#0x00000000,d1			/* set font bg color */
		or.l	d1,d0
		move.l	d0,(a2)					/* set tile line */
		dbra	d2,7b

		move.l	#0xC0000000,(a1)		/* write CRAM address 0 */
		move.l	#0x00000CCC,(a2)		/* entry 0 (black) and 1 (lt gray) BGR */
		move.l	#0xC0200000,(a1)		/* write CRAM address 32 */
		move.l	#0x000000A0,(a2)		/* entry 16 (black) BGR and 17 (green) */
		move.l	#0xC0400000,(a1)		/* write CRAM address 64 */
		move.l	#0x0000000A,(a2)		/* entry 32 (black) BGR and 33 (red) */
.ifdef BOOT_STAGE
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x00EE,(0xC00000).l	/* stage: YELLOW = font + CRAM done */
.endif

		move.b	#0,(0xA15107)			/* clear RV - allow SH2 to access ROM */
		move.w	#0,(JoypadState)		/* controller 1 */
		move.l	#0,(VBlankCounter)		/* clear the vblank count */
.ifdef BOOT_BEACON
		/* BOOT BEACON (2026-09-07, MiSTer will not boot): the backdrop
		 * (CRAM 0) tells the stage. BLUE = waiting for the master's
		 * M_OK, its green tint = the master's own progress word on
		 * COMM12 (1 started, 2 bss cleared, 3 ramtext copied, 4 past
		 * the handshake); GREEN = M_OK seen, waiting for S_OK; YELLOW =
		 * both SH-2s up; WHITE = handing off to the shim's main. */
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x0800,(0xC00000).l
.endif
.ifdef BOOT_STAGE
	8:	bra.s	8b						/* BLUE = RV cleared; halt here */
.endif
	0:
.ifdef BOOT_BEACON
		move.w	(0xA1512C).l,d0			/* master's stage word (COMM12) */
		and.w	#7,d0
		lsl.w	#5,d0					/* green steps of 0x20 */
		or.w	#0x0800,d0
		move.l	#0xC0000000,(0xC00004).l
		move.w	d0,(0xC00000).l
.endif
.ifdef BOOT_ROMCHK
		bra.s	0b							/* probe: stay here, show the tint */
.endif
		cmp.l	#0x4D5F4F4B,(MARS_COMM0)	/* M_OK */
		bne.s	0b							/* wait for primary ok */
.ifdef BOOT_BEACON
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x00A0,(0xC00000).l	/* green: M_OK */
.endif
	1:
		cmp.l	#0x535F4F4B,(MARS_COMM4)	/* S_OK */
		bne.s	1b							/* wait for secondary ok */
.ifdef BOOT_BEACON
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x00EE,(0xC00000).l	/* yellow: both SH-2s up */
.endif

		move.w	(0xA15100),d0
		or.w	#0x8000,d0
		move.w	d0,(0xA15100)		/* set FM - allow SH2 access to MARS hw */
		move.w	#0xACED,(MARS_COMM8)	/* MD-ready level: releases both SH-2s */

		/* PARK THE Z80 (Mike heard it: "sound clipping" on ares — no
		 * sound is wired, the Z80 was free-running uninitialised RAM
		 * into the YM2612/PSG from power-on; every MAME run was
		 * -sound none so it was never audible before). HOLD IT IN
		 * RESET, permanently: one write, no bus-grant poll (two poll
		 * variants both hung boot here — grant never arrives in this
		 * config), no RAM program needed. A reset-held Z80 is silent,
		 * and the joypad path's bus-request toggles cannot wake it.
		 * When real sound lands, a proper driver upload replaces this. */
		move.w	#0x000,(0xA11200)	/* assert Z80 reset, forever */

		/* MUTE THE PSG (Mike, LOOP 13: "still z80 clipping" with the
		 * park verified in place). Z80 reset also resets the YM2612 —
		 * but NOT the PSG, which lives in the VDP: any channel keyed
		 * during the free-run window before the park (or by the
		 * emulator's power-on PSG state) sounds FOREVER, and nothing
		 * ever wrote the attenuation-off latches. %1cc11111 = channel
		 * cc volume off. */
		move.b	#0x9F,(0xC00011)	/* tone 0 att 15 (off) */
		move.b	#0xBF,(0xC00011)	/* tone 1 att 15 */
		move.b	#0xDF,(0xC00011)	/* tone 2 att 15 */
		move.b	#0xFF,(0xC00011)	/* noise  att 15 */

		/* Pad port init (canonical, per d32xr crt0 + SGDK JOY_reset): TH as
		 * an OUTPUT (CTRL bit6) idling HIGH on both ports. Was never done —
		 * the six-button phase table assumes the first transition each frame
		 * is a driven high->low edge; without CTRL setup TH is an input and
		 * the probe writes may not reach the controller at all. */
		move.b	#0x40,(IO_CTRL1)	/* 1P: TH output */
		move.b	#0x40,(IO_CTRL2)	/* 2P: TH output */
		move.b	#0x40,(IO_DATA1)	/* 1P: TH idle high */
		move.b	#0x40,(IO_DATA2)	/* 2P: TH idle high */

		lea		0xFFBFF0,sp			/* boot/shim stack, clear of game work RAM */
.ifdef BOOT_BEACON
		move.l	#0xC0000000,(0xC00004).l
		move.w	#0x0EEE,(0xC00000).l	/* white: into main */
.endif

		jmp		main				/* RAM-resident; main sets RV=1 itself —
									   setting RV while executing from the
									   0x880000 window kills the fetch */

;// VDP register initialization values
InitVDPRegs:
		dc.b	0x14			/* 80 = HBL INT ON (level 4 = arcade IRQ4), read H/V cnt */
		dc.b	0x54			/* 81 = disp on, VBL INT OFF (adapter level-6 vector
								 * points at a 0x880000-window trampoline — forbidden
								 * under RV=1; ares enforces), DMA on, V28 mode */
		dc.b	0xC000 / 0x400	/* 82 = Name Tbl A */
		dc.b	0xB000 / 0x400	/* 83 = Name Tbl W */
		dc.b	0xE000 / 0x2000	/* 84 = Name Tbl B */
		dc.b	0xF000 / 0x200	/* 85 = Sprite Attr Tbl — moved from
								 * 0xFE00 (P3): H40 masks the base to
								 * 1KB alignment, so 0xFE00 aliased
								 * onto the HSCROLL table at 0xFC00;
								 * 0xF000 is aligned, free VRAM, and
								 * md_bg_palette zeroes it (real-HW
								 * boot garbage was never cleared) */
		dc.b	0x00			/* 86 = always 0 */
		dc.b	0x00			/* 87 = BG color */
		dc.b	0x00			/* 88 = always 0 */
		dc.b	0x00			/* 89 = always 0 */
.ifdef PC_SAMP
		dc.b	0x37			/* 8A = 55: H-int at 55/111/167/223 (sampler) */
.else
		dc.b	0xDF			/* 8A = HINT counter 223: one IRQ4 at the last
								 * active line = vblank cadence, arcade-style */
.endif
		dc.b	0x00			/* 8B = no EXT INT, full scroll */
		dc.b	0x81			/* 8C = H40 mode, no lace, no shadow/hilite */
		dc.b	0xFC00 / 0x400	/* 8D = HScroll Tbl */
		dc.b	0x00			/* 8E = always 0 */
		dc.b	0x02			/* 8F = data INC */
		dc.b	0x01			/* 90 = Scroll Size */
		dc.b	0x00			/* 91 = W Pos H = left */
		dc.b	0x00			/* 92 = W Pos V = top */

	.align  2

/****************************************************************************
 * All code below this line runs from Work RAM
 ***************************************************************************/

	.section .data

	.global read_joypad
read_joypad:
		PAUSE_Z80
		lea		IO_DATA1,a0
		move.b	5(sp),d0
		beq.s	1f
		lea		IO_DATA2,a0
	1:
		move.w	d2,-(sp)
		/* Mask interrupts across the 4-phase probe: a VINT landing between
		 * TH toggles desyncs the controller's six-button counter and returns
		 * garbage on real hardware (emulators are more forgiving). */
		move.w	sr,-(sp)
		move.w	#0x2700,sr
		bsr.s	get_input		/* - 0 s a 0 0 d u - 1 c b r l d u */
		move.w	d2,d1
		bsr.s	get_input		/* - 0 s a 0 0 d u - 1 c b r l d u */
		bsr.s	get_input		/* - 0 s a 0 0 0 0 - 1 c b m x y z */
		move.w	d2,d0
		bsr.s	get_input		/* - 0 s a 1 1 1 1 - 1 c b r l d u */
		move.w	(sp)+,sr		/* phases done; timing no longer critical */
		/* SGDK-canon detection. The strict 1111 test is KNOWN-FRAGILE:
		 * SGDK's own source documents six-button pads whose 4th phase reads
		 * 0s ("should be read as 1 but in some case we read 0" — wireless
		 * receivers especially), so requiring exact 1111 kills real pads.
		 * The old any-bit test failed the other way (3-button d/u idle HIGH
		 * faked six-button -> phantom M X Y Z from phase 3). Canon threads
		 * it: six-button iff the 3rd TH-low phase shows the 0000 marker AND
		 * the 4th TH-low r/l slots are not hard-zero (wired 0 on a 3-button
		 * pad; up+down-both is the impossible combo this guards against). */
		/* FIELD REVERT / DIAGNOSE (if a tester's pad misbehaves): the live probe
		 * word is on the pad-test HUD -- pause menu -> METRICS, the RAW: and lamp
		 * rows show exactly what this reads. A real six-button pad dropping to
		 * three-button here means this test is too STRICT; a three-button or
		 * wireless pad faking six-button (ghost MODE/X/Y/Z) means too LOOSE. To
		 * back the whole phantom-button fix out (68K + the SH-2 MODE-debounce +
		 * the START-clears-overlays companions): `git revert e5603cf`. To relax
		 * only this gate, drop the 0x0C00 r/l check just below and keep the
		 * phase-3 marker test alone. Origin: smokemonster's field report. */
		andi.w	#0x0C00,d2
		beq.s	9f				/* r/l slots hard-0: three-button pad */
		move.w	d0,d2
		andi.w	#0x0F00,d2
		beq.s	common			/* phase-3 0000 marker present: six-button */
	9:
		move.w	#0x010F,d0		/* three button pad: neutral M X Y Z */
	common:
		lsl.b	#4,d0			/* - 0 s a 0 0 0 0 m x y z 0 0 0 0 */
		lsl.w	#4,d0			/* 0 0 0 0 m x y z 0 0 0 0 0 0 0 0 */
		andi.w	#0x303F,d1		/* 0 0 s a 0 0 0 0 0 0 c b r l d u */
		move.b	d1,d0			/* 0 0 0 0 m x y z 0 0 c b r l d u */
		lsr.w	#6,d1			/* 0 0 0 0 0 0 0 0 s a 0 0 0 0 0 0 */
		or.w	d1,d0			/* 0 0 0 0 m x y z s a c b r l d u */
		eori.w	#0x1FFF,d0		/* 0 0 0 1 M X Y Z S A C B R L D U */
		RESUME_Z80
		move.w	(sp)+,d2
		rts

get_input:
		/* Settle time after each TH toggle: wired pads answer in ns, but
		 * wireless receivers/adapters latch async and return STALE phases
		 * when probed ~1us after the edge — they then fail the six-button
		 * signature and demote to 3-button (extended buttons dead). ~8 nops
		 * = ~4us per edge; whole 4-phase probe still well under 50us. */
		move.b	#0x00,(a0)
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		move.b	(a0),d2
		move.b	#0x40,(a0)
		lsl.w	#8,d2
		nop
		nop
		nop
		nop
		nop
		nop
		move.b	(a0),d2
		rts

	.global _vblank
_vblank:
.ifdef PC_SAMP
		/* PC SAMPLER PROBE (2026-09-06): reg 10 = 55 makes the H-int fire
		 * at lines 55/111/167/223; the three early ones only record the
		 * interrupted PC into a 127-long ring at 0xFFA200 (index word
		 * 0xFFA3FE) and return. The 223 one is the real vint. */
		movem.l	d0/a0,-(sp)
		move.w	(0xC00008).l,d0
		cmp.w	#0xDE00,d0
		bhs.s	9f
		move.l	d1,-(sp)
		move.w	d0,d1				/* V|H */
		move.b	(0xFFF109).w,d1		/* low byte = game object index */
		move.w	(0xFFA3FE).w,d0
		addq.w	#1,(0xFFA3FE).w
		and.w	#63,d0
		add.w	d0,d0
		lea		(0xFFA300).w,a0
		move.w	d1,(a0,d0.w)		/* V of the sample */
		add.w	d0,d0
		lea		(0xFFA200).w,a0
		move.l	14(sp),(a0,d0.w)	/* interrupted PC (d1 4 + d0/a0 8 + SR 2) */
		move.l	(sp)+,d1
		movem.l	(sp)+,d0/a0
		rte
	9:	movem.l	(sp)+,d0/a0
.endif
		move.l	2(sp),(0xFFB0F8)	/* diagnostics: interrupted (game) PC */
		movem.l	d0-d7/a0-a6,-(sp)
		/* burn-down aid: snapshot 16 words of the interrupted stack to
		 * 0xFFB100 — when a missed rebase pointer drops the game PC low,
		 * the return-address chain here names the jsr that did it. */
		lea		66(sp),a0			/* movem 60 bytes + frame SR2/PC4 */
		lea		0xFFB100,a1
		moveq	#15,d0
	9:	move.w	(a0)+,(a1)+
		dbf		d0,9b
		jsr		shim_vblank			/* C shim: MCU duties (md_main.c) */
		movem.l	(sp)+,d0-d7/a0-a6
		tst.w	(game_running)
		beq.s	1f
.ifdef FM_GATE
		/* LOOP 23 — RTE TRAMPOLINE. The game's vint upload must run at
		 * FM=0 (its stores are DELIBERATELY ungated), so the FM raise
		 * moves to part B, entered by hijacking the frame the game's
		 * rte pops: save the real (SR,PC), plant a fake frame whose SR
		 * masks interrupts (part B must not be re-entered) and whose
		 * PC is fmgate_ret. Every exit path of the game handler ends
		 * in that rte, so any internal early-out still lands here. */
		move.w	(sp),(fmgate_sr)
		move.l	2(sp),(fmgate_pc)
		move.w	#0x2700,(sp)
		move.l	#fmgate_ret,2(sp)
		jmp		(GAME_IRQ4).l		/* game IRQ4; its rte -> fmgate_ret */
	1:
.ifdef POST_LATE
		movem.l	d0-d1/a0-a1,-(sp)
		jsr		r60_late_post
		movem.l	(sp)+,d0-d1/a0-a1
.endif
		jsr		fmgate_partb		/* boot path (no game handler): the
									 * real frame is still intact */
		rte
fmgate_ret:							/* via the game's rte, SR=2700 */
.ifdef BOOT_GAMERATE
		/* GAME FRAMES, COUNTED WHERE THEY HAPPEN (LOOP27 68). Every exit
		 * path of the game's IRQ4 lands here, so this counter is exactly
		 * "the game advanced a frame" — scene-independent, unlike the
		 * scene timer, which runs at different rates (and backwards) in
		 * different attract scenes and made the first comparison
		 * meaningless. */
		addq.w	#1,(0xFFA18E).l
.endif
.ifdef POST_LATE
		movem.l	d0-d1/a0-a1,-(sp)	/* the game's live scratch regs */
		jsr		r60_late_post		/* post+push AFTER the game's vint */
		movem.l	(sp)+,d0-d1/a0-a1
.endif
		/* GAME-HANDLER LENGTH PROBE (2026-09-06): V at the game's rte,
		 * ring[vint & 63] at 0xFFA300 (entry V | idle flag at 0xFFA380,
		 * shim_vblank). The game runs its whole frame inside IRQ4, so
		 * end-V - entry-V is the frame's 68K work. */
		movem.l	d0-d1/a0,-(sp)
		move.w	(0xFFB0F0),d0
		and.w	#63,d0
		add.w	d0,d0
		lea		(0xFFA300),a0
		move.w	(0xC00008),d1
		move.b	(0xA1512F).l,d1		/* low byte = vblank count (COMM14) */
		move.w	d1,(a0,d0.w)
		movem.l	(sp)+,d0-d1/a0
		jsr		fmgate_partb
		move.l	(fmgate_pc),-(sp)	/* rebuild the real frame */
		move.w	(fmgate_sr),-(sp)
		rte

	/* PART B — publish, raise FM, post. No spin: the SH-2 drops FM
	 * itself and clears COMM0 (the ack) at window end. Defers instead
	 * of racing: a still-running window (COMM0 != 0) or an interrupted
	 * PC inside a gated span/thunk region means the raise would either
	 * collide or strand a store mid-gate — skip this vint's window
	 * (same cost class as a V-gate skip; counted in fmgate_defer). */
fmgate_partb:
		movem.l	d0-d1/a0,-(sp)
		move.w	(fmgate_wcmd),d0
		beq.s	9f					/* no window wanted this vint */
		tst.w	(0xA15120).l		/* COMM0: previous window running? */
		bne.s	8f
		move.l	(0xFFB0F8),d1		/* interrupted game PC */
		lea		(fmgate_spans),a0	/* u32 pairs, 0-terminated */
	0:	move.l	(a0)+,d0
		beq.s	1f					/* table end: clear to raise */
		cmp.l	d0,d1
		blo.s	2f					/* pc < start: next span */
		cmp.l	(a0),d1
		bls.s	8f					/* start <= pc <= end: defer */
	2:	addq.l	#4,a0
		bra.s	0b
	1:	moveq	#0,d0
		move.b	(0xFFB043),d0		/* BANK_SHADOW byte, widened as the
									 * C path's uint8 promotion did */
		move.w	d0,(0xA15122).l		/* comm2 */
		move.w	(0xC00008).l,d0		/* live V heartbeat */
		lsr.w	#8,d0
		ori.w	#0xD000,d0
		move.w	d0,(0xA1512C).l		/* comm12 — BEFORE the post */
		/* LOOP29 229: this post stays RAW. 226 masked it and carried the
		 * round here; that build deferred 57 windows across the attract
		 * (vi70/vi71: 0) and the round field's dirt was never the cause
		 * of the same-round return anyway (226 measured). The SH-2 masks
		 * the low 13 bits it uses; the round it reads here can carry
		 * regions 13-15 by phase and md_round's guarded installs are the
		 * belt. Revisit with the C-side posts if the round channel is
		 * ever made authoritative (214: 0xFFF148 through the mailbox). */
		move.w	(0xFFB9FE),(0xA1512A).l	/* comm10 = live tile dirt */
		ori.w	#0x8000,(0xA15100).l	/* FM=1: SH-2 owns the FB */
		move.w	(fmgate_wcmd),(0xA15120).l	/* post the window */
		move.w	#1,(fmgate_posted)
		bra.s	7f
	8:	addq.w	#1,(fmgate_defer)
		clr.w	(fmgate_posted)
	7:	clr.w	(fmgate_wcmd)
	9:	movem.l	(sp)+,d0-d1/a0
		rts
_hblank:
		rte
.else
		jmp		(GAME_IRQ4).l		/* game IRQ4 handler (rebased high copy);
									   its rte pops our frame */
	1:
_hblank:
		rte
.endif
