#!/usr/bin/env python3
"""The actor palette table: every sprite colour the game can ask for.

    python3 tools/actor_palettes.py > sh_src/actor_pal.h

LOOP-DECOMPILE 77/79. `build_palette_upload_queue` at 0x3BEC is the ONLY
writer above palette line 63:

    3c20:  lea 0x840800,a1 ; lea (2,a1,d0.w),a1    dest, d0 = $0A * 32
    3c3a:  lea 0x242a0,a1  ; lea (0,a1,d0.w),a1    src,  d0 = $0B * 28
    3c5a:  the drain copies exactly 7 longwords = 28 bytes

So a sprite palette is 14 words copied VERBATIM out of rom into colours
1-14 of the line. Nothing is computed, nothing is allocated, and the
complete set the program can request is the immediates written to $0B
plus the three per-scene id tables. There is no reason for any refuse
rule to starve one: bake the table.
"""
import re, sys, collections

ROM = 'roms/altbeast/prog68k.bin'
STREAM = 'docs/audit/code_stream.txt'
BASE, STRIDE, NREC = 0x242A0, 28, 176
# Every table a $0B write indexes, found by reading the six indexed write
# sites (LOOP-DECOMPILE 79). (base, count).
ID_TABLES = (
    (0x073DA, 5),    # per-scene actor palette, sites 0x5F2E and 0x5FEC
    (0x092EA, 5),    # per-scene actor palette, site 0x9090
    (0x173A0, 5),    # per-scene actor palette, site 0x16B7E
    (0x026CC, 16),   # THE TRANSFORM CYCLE, site 0x24D4, indexed by
                     # ($22 & 31) >> 1 -- the object's own anim timer, so it
                     # steps every SECOND frame
    (0x10136, 4),    # site 0xFC36, indexed by (d0 >> 2) & 3
)


def md(v):
    """S16 word -> the MD's 3-bit-per-channel colour, as bake_tilecram does."""
    r = (((v >> 0) & 0xF) << 1 | ((v >> 12) & 1)) >> 2
    g = (((v >> 4) & 0xF) << 1 | ((v >> 13) & 1)) >> 2
    b = (((v >> 8) & 0xF) << 1 | ((v >> 14) & 1)) >> 2
    return (b << 9) | (g << 5) | (r << 1)


def used(rom):
    ids = set()
    W = re.compile(r'^#(-?\d+),%(?:fp|a\d)@\(11\)$')
    for ln in open(STREAM):
        f = ln.rstrip('\n').split('\t')
        if len(f) >= 4 and f[2].startswith('move'):
            m = W.match(f[3])
            if m:
                ids.add(int(m.group(1)) & 0xFF)
    for t, n in ID_TABLES:
        ids.update(rom[t:t + n])
    return {i for i in ids if i < NREC}


def main():
    rom = open(ROM, 'rb').read()
    u = sorted(used(rom))
    print('/* generated by tools/actor_palettes.py — the SPRITE palette')
    print(' * table at rom 0x%05X: %d records of %d bytes, copied verbatim'
          % (BASE, NREC, STRIDE))
    print(' * into colours 1-14 of palette line ($0A) by the queue drain at')
    print(' * 0x3C5A. Index is object $0B. See LOOP-DECOMPILE 77 and 79. */')
    print('#define ACTOR_PAL_N      %d' % NREC)
    print('#define ACTOR_PAL_COLS   14')
    print('/* the %d indices the program can actually request: every $0B'
          % len(u))
    print(' * immediate in the code, plus the three per-scene id tables at')
    print(' * 0x73DA, 0x92EA and 0x173A0. */')
    print('static const unsigned char actor_pal_used[%d] = {%s};'
          % (len(u), ','.join(str(x) for x in u)))
    print('static const unsigned short actor_pal[%d][14] = {' % NREC)
    for i in range(NREC):
        o = BASE + i * STRIDE
        w = [int.from_bytes(rom[o + 2 * k:o + 2 * k + 2], 'big')
             for k in range(14)]
        print('  {%s},%s' % (','.join('0x%04X' % md(x) for x in w),
                             '' if i in u else '   /* unused */'))
    print('};')
    sys.stderr.write('%d records, %d requested by the program\n' % (NREC, len(u)))


if __name__ == '__main__':
    main()
