#!/usr/bin/env python3
"""Per-column colour-set extents for every tilemap page of every scene,
from the rom -- the static half of the master's maps drain.

`build_maps` / `bm_scan_rows` (sh_src/m_main.c ~2534) walks 44x28 cells
of both planes every generation to learn WHICH colour sets the viewport
holds and at which priority (tcount is consumed only as presence:
bm_tail_body `tcount[...] != 0`; col_lvl/amb_col come from the cat bit).
Tile RAM has no in-play writer (LOOP-DECOMPILE 99), so that answer is a
function of the rom tilemap and the scroll. This bakes, per scene, per
page, per column: (set, cat, first row, last row) for every set the
column holds. A viewport is then 44 columns x (up to 2 quadrant row
ranges) of extent compares instead of 2,464 cell reads per plane.

Proven exact against bm_scan_rows's own window formula on 4,000 random
(pq, vx0, vy0) windows (LOOP-DECOMPILE 101), 0 mismatches.

    tools/bake_setcols.py [--emit sh_src/setcols_md.h] [--stats]

Format emitted: for each scene, `setcol_idx[10][65]` (uint16 offsets into
that scene's entry array, column c spans idx[c]..idx[c+1]) and
`setcol_ent[]` of uint8 triples {set | cat<<7, first_row, last_row}.
"""
import struct, argparse, sys
ROM = 'roms/altbeast/prog68k.bin'

def unpack(rom, base):
    hi = bytearray(); p = base
    while len(hi) < 20480:
        cnt, val = rom[p], rom[p + 1]; p += 2; hi += bytes([val]) * (cnt + 1)
    lo = bytearray()
    while len(lo) < 20480:
        b = rom[p]; p += 1
        if b: lo.append(b)
        else:
            n = rom[p]; p += 1; lo += bytes(n if n else 1)
    return [(hi[i] << 8) | lo[i] for i in range(20480)]

def bake_scene(W):
    pages = []
    for pg in range(10):
        cols = []
        for c in range(64):
            ext = {}
            for r in range(32):
                w = W[pg * 2048 + r * 64 + c]
                if w:
                    k = ((w >> 6) & 0x7F, 1 if w & 0x8000 else 0)
                    lo, hi = ext.get(k, (r, r)); ext[k] = (min(lo, r), max(hi, r))
            cols.append(sorted((s | (cat << 7), lo, hi) for (s, cat), (lo, hi) in ext.items()))
        pages.append(cols)
    return pages

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--emit'); ap.add_argument('--stats', action='store_true')
    a = ap.parse_args()
    rom = open(ROM, 'rb').read()
    scenes = []
    for sc in range(5):
        d = 0x1CE2 + sc * 6
        base = struct.unpack('>I', rom[d + 2:d + 6])[0]
        scenes.append(bake_scene(unpack(rom, base)))
    if a.stats or not a.emit:
        for sc, pages in enumerate(scenes):
            n = sum(len(c) for p in pages for c in p)
            mx = max(len(c) for p in pages for c in p)
            print(f"scene {sc}: {n} entries ({n * 3} bytes), max {mx} per column, "
                  f"mean {n / 640:.1f}")
    if a.emit:
        with open(a.emit, 'w') as fh:
            fh.write("/* GENERATED by tools/bake_setcols.py (LOOP-DECOMPILE 101).\n"
                     " * Per scene, per page, per column: the colour sets the column\n"
                     " * holds with their row extent. {set | cat<<7, first, last}.\n"
                     " * A 44x28 viewport = for each of its columns, each quadrant's\n"
                     " * row range: entries whose extent overlaps it are present. */\n")
            fh.write("#define SETCOL_SCENES 5\n")
            for sc, pages in enumerate(scenes):
                idx = []; ent = []
                for pg in pages:
                    row = []
                    for c in pg:
                        row.append(len(ent)); ent.extend(c)
                    row.append(len(ent)); idx.append(row)
                fh.write(f"static const uint16_t setcol_idx{sc}[10][65] = {{\n")
                for row in idx:
                    fh.write("    { " + ", ".join(str(x) for x in row) + " },\n")
                fh.write("};\n")
                fh.write(f"static const uint8_t setcol_ent{sc}[{max(1, len(ent) * 3)}] = {{\n")
                for i in range(0, len(ent), 8):
                    fh.write("    " + " ".join(f"{s},{lo},{hi}," for s, lo, hi in ent[i:i + 8]) + "\n")
                fh.write("};\n")
            fh.write("static const uint16_t (*const setcol_idx[SETCOL_SCENES])[65] = { "
                     + ", ".join(f"setcol_idx{s}" for s in range(5)) + " };\n")
            fh.write("static const uint8_t *const setcol_ent[SETCOL_SCENES] = { "
                     + ", ".join(f"setcol_ent{s}" for s in range(5)) + " };\n")
        print("wrote", a.emit)

if __name__ == '__main__':
    main()
