#!/usr/bin/env python3
"""Per-scene 1-bit opacity masks for the class-2 (partial) cat-1 tiles --
the slave's punched loop reads one SDRAM byte per sprite row instead of
eight cart bytes (NOTES-FROM-DECOMPILE 34, LOOP29 247).

Inputs: sh_src/cat1hole.bin (two bits per cell, class 2 = per pixel),
the rom tilemap (unpacker with n+1 zero runs, LOOP29 243) for the tile
code of every class-2 FG cell, sh_src/tiles.bin (8bpp) for opacity.
Emits sh_src/cat1mask.h: per scene a SORTED array of tile codes and a
parallel array of 8-byte masks (bit 7-(px) of byte py = pixel opaque);
the name-table pass binary-searches the code and stores the index.

    tools/bake_cat1mask.py [--stats]
"""
import os, struct, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = os.environ.get('GAME', 'altbeast')
ROM = os.path.join(ROOT, 'roms', GAME, 'prog68k.bin')
rom = open(ROM, 'rb').read()
tiles = open(os.path.join(ROOT, 'sh_src', 'tiles.bin'), 'rb').read()
hole = open(os.path.join(ROOT, 'sh_src', 'cat1hole.bin'), 'rb').read()
SCENE_TABLE, SCENES = 0x1CE2, 5

def unpack(base):
    hi = bytearray(); p = base
    while len(hi) < 20480:
        cnt, val = rom[p], rom[p + 1]; p += 2; hi += bytes([val]) * (cnt + 1)
    lo = bytearray()
    while len(lo) < 20480:
        b = rom[p]; p += 1
        if b: lo.append(b)
        else:
            n = rom[p]; p += 1; lo += bytes(n + 1)   # zero run = n+1 (LOOP29 243)
    lo = lo[:20480]
    return [(hi[i] << 8) | lo[i] for i in range(20480)]

def hole_get(s, n):
    return (hole[s * 5120 + (n >> 2)] >> ((3 - (n & 3)) * 2)) & 3

out = []
stats = []
for s in range(SCENES):
    d = SCENE_TABLE + s * 6
    base = struct.unpack('>I', rom[d + 2:d + 6])[0]
    W = unpack(base)
    codes = set()
    for n in range(5 * 2048):                      # FG pages 0-4 only
        if hole_get(s, n) == 2:
            w = W[n]
            code = w & 0x1FFF
            if code & 0x1000:
                # bank-1 codes: the runtime adds bank1*0x1000 (the game's
                # tile bank); the bake keeps the raw 13-bit code and the
                # runtime searches with the same raw code (see m_main.c)
                pass
            codes.add(code)
    codes = sorted(codes)
    masks = []
    for c in codes:
        t = tiles[c * 64:(c + 1) * 64]
        m = bytes(sum(((1 << (7 - px)) if t[py * 8 + px] else 0) for px in range(8)) for py in range(8))
        masks.append(m)
    out.append((codes, masks))
    stats.append((s, len(codes), len(codes) * 8))

with open(os.path.join(ROOT, 'sh_src', 'cat1mask.h'), 'w') as fh:
    fh.write('/* generated by tools/bake_cat1mask.py (LOOP29 247): per scene the sorted\n'
             ' * raw 13-bit tile codes of the class-2 cat-1 tiles and their 8-byte\n'
             ' * 1-bit opacity masks (byte py, bit 7-px). */\n')
    fh.write('#define CAT1MASK_SCENES %d\n' % SCENES)
    fh.write('#define CAT1MASK_MAX %d\n' % max(len(c) for c, _ in out))
    for s, (codes, masks) in enumerate(out):
        fh.write('static const unsigned short cat1mask_code%d[%d] = {%s};\n' % (s, len(codes), ','.join(str(c) for c in codes)))
        fh.write('static const unsigned char cat1mask_bits%d[%d] = {%s};\n' % (s, len(masks) * 8, ','.join(str(b) for m in masks for b in m)))
    fh.write('static const unsigned short cat1mask_n[CAT1MASK_SCENES] = {%s};\n' % ','.join(str(len(c)) for c, _ in out))
    fh.write('static const unsigned short *const cat1mask_code[CAT1MASK_SCENES] = {%s};\n' % ','.join('cat1mask_code%d' % s for s in range(SCENES)))
    fh.write('static const unsigned char *const cat1mask_bits[CAT1MASK_SCENES] = {%s};\n' % ','.join('cat1mask_bits%d' % s for s in range(SCENES)))
for s, n, b in stats:
    print('scene %d: %3d class-2 tiles, %5d bytes of masks' % (s, n, b))
print('wrote sh_src/cat1mask.h')
