#!/usr/bin/env python3
"""Bake the CAT1 VISIBILITY bitmaps: which cat1 tiles can actually be seen.

    tools/bake_cat1vis.py [--stats]

A background cat1 tile sitting under a FULLY OPAQUE foreground tile is
never reached by the priority mixer, so it contributes nothing to the
final image and never needs composing. That is not an inference:
`srcref/jtcores/cores/s16/hdl/jts16_prio.v:83-95` tests lyr1 (scr1, the
foreground) before lyr2 (scr2, the background) unconditionally, and
tile_or_obj (line 58) returns the sprite or the tile but never nothing.
So an opaque foreground pixel ends the search above the background.

Measured 50% of PAGE-0 cat1 cells across the five scenes, 83% in scene 2
(docs/log/LOOP-DECOMPILE.md 57, 58).

MIND THE DENOMINATOR -- two populations, one measurement (NOTES 93,
LOOP29 303). Occlusion can only be TESTED where BG page 0 sits under FG
page 7, so entry 57's 50% is 2,373 of the **4,724 PAGE-0 cat1 cells**.
The --stats table below divides the same 2,373 by cat1 cells across all
TEN tilemap pages (23,432) and so reports 10%. Both are right; they are
not the same question. Verified exactly: page-0 cat1 = 4,724 and scene 2
= 83.4%, reproducing entry 57 to the cell.

The one that SIZES a card is the page-0 figure, because cells outside the
composable BG page are never composed and so cannot be saved.

Emits, beside sh_src/cat1map.bin (which says WHICH tiles are cat1):
  sh_src/cat1vis.bin   1 = this cat1 tile is VISIBLE and must be composed
                       0 = occluded, or not cat1 at all
  sh_src/cat1vis.h     counts per scene
Same geometry as cat1map: one bit per tile, MSB first, 2560 B per scene.
"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = os.environ.get('GAME', 'altbeast')
ROM = os.path.join(ROOT, 'roms', GAME, 'prog68k.bin')
TILES = os.path.join(ROOT, 'sh_src', 'tiles.bin')

SCENE_TABLE, SCENES, TILES_N = 0x1CE2, 5, 20480
BYTES_PER_SCENE = TILES_N // 8
BG_PAGE, FG_PAGE = 0, 7          # scr2 draws page 0, scr1 page 7 (entry 11)


def hi_pass(rom, src):
    out = bytearray(); p = src
    while len(out) < TILES_N and p + 1 < len(rom):
        out.extend(bytes([rom[p + 1]]) * (rom[p] + 1)); p += 2
    return out[:TILES_N], p


def lo_pass(rom, src):
    out = bytearray(); p = src
    while len(out) < TILES_N and p < len(rom):
        d0 = rom[p]; p += 1
        if d0:
            out.append(d0); continue
        d2 = rom[p]; p += 1
        if d2 == 0:
            out.append(0); continue
        out.extend(b'\x00' * d2)
    return out[:TILES_N]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--stats', action='store_true')
    a = ap.parse_args()
    with open(ROM, 'rb') as fh:
        rom = fh.read()
    if not os.path.exists(TILES):
        sys.exit('sh_src/tiles.bin missing — run tools/gen_tiles.py first')
    with open(TILES, 'rb') as fh:
        tiles = fh.read()

    def fully_opaque(idx):
        o = idx * 64
        if o + 64 > len(tiles):
            return False
        return 0 not in tiles[o:o + 64]

    maps, stats = [], []
    for s in range(SCENES):
        o = SCENE_TABLE + 6 * s
        ptr = int.from_bytes(rom[o + 2:o + 6], 'big')
        hi, after = hi_pass(rom, ptr)
        lo = lo_pass(rom, after)
        words = [(hi[i] << 8) | lo[i] for i in range(TILES_N)]
        bits = bytearray(BYTES_PER_SCENE)
        cat1 = vis = 0
        for i in range(TILES_N):
            if not (words[i] & 0x8000):
                continue
            cat1 += 1
            page, cell = divmod(i, 2048)
            if page == BG_PAGE and fully_opaque(words[FG_PAGE * 2048 + cell] & 0x1FFF):
                continue                       # occluded: leave the bit clear
            bits[i >> 3] |= 0x80 >> (i & 7)
            vis += 1
        maps.append(bits)
        stats.append((s, cat1, vis))

    print('scene   cat1   visible   occluded   saving')
    print('  (cat1/saving are over ALL TEN tilemap pages; the figure that')
    print('   sizes a card is occluded / PAGE-0 cat1 = 50.2% -- NOTES 93)')
    tc = tv = 0
    for s, cat1, vis in stats:
        tc += cat1; tv += vis
        print('  %d    %5d   %5d     %5d     %3.0f%%'
              % (s, cat1, vis, cat1 - vis,
                 100.0 * (cat1 - vis) / cat1 if cat1 else 0))
    print('total  %5d   %5d     %5d     %3.0f%%'
          % (tc, tv, tc - tv, 100.0 * (tc - tv) / tc if tc else 0))
    if a.stats:
        return
    with open(os.path.join(ROOT, 'sh_src', 'cat1vis.bin'), 'wb') as fh:
        for m in maps:
            fh.write(m)
    with open(os.path.join(ROOT, 'sh_src', 'cat1vis.h'), 'w') as fh:
        fh.write('/* generated by tools/bake_cat1vis.py — 1 = this cat1 tile\n'
                 ' * is VISIBLE and must be composed; 0 = occluded by a fully\n'
                 ' * opaque foreground tile and never reached by the mixer\n'
                 ' * (jts16_prio.v:83-95). Same geometry as cat1map.bin. */\n')
        fh.write('#define CAT1VIS_BYTES_PER_SCENE %d\n' % BYTES_PER_SCENE)
        fh.write('static const unsigned short cat1vis_counts[%d] = { %s };\n'
                 % (SCENES, ', '.join(str(v) for _, _, v in stats)))
    print('wrote sh_src/cat1vis.bin and sh_src/cat1vis.h')


if __name__ == '__main__':
    main()
