#!/usr/bin/env python3
"""The cat-1 HOLE map for fold 1's sprite suppress: two bits per cell.

LOOP-DECOMPILE 65 / LOOP29 175: with the framebuffer cat-1 pass gone
(C1_NOFB) a sprite pixel has to be SUPPRESSED where a cat-1 cell covers
it so the MD's plane A HIGH shows through. Per cell the answer is one
of three, and it is rom data (the tile word's priority bit + the art):

    0  NO HOLE      not cat-1, or cat-1 on a tile with no pixels
    1  SUPPRESS ALL the cat-1 tile is fully opaque: whole cell
    2  PER PIXEL    the tile has transparent pixels: consult the art

Same cell geometry as sh_src/cat1map.bin (tile n of scene s), two bits
per cell MSB-first: byte s*5120 + n/4, field (3 - n%4)*2. All ten pages
are baked; the level's FOREGROUND pages are 0-4 and the background 5-9
(the page tables at 0x40F0/0x4100, LOOP-DECOMPILE 92), and only a
foreground cat-1 cell beats a sprite (level 4 against pp=2's 4,
entry 59); background cat-1 (level 2) loses to every sprite.

Tile art comes from sh_src/tiles.bin indexed by the 13-bit tile index,
the same convention bake_cat1vis.py uses.

    tools/bake_cat1hole.py [--stats]
"""
import os, sys, argparse
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = os.environ.get('GAME', 'altbeast')
ROM = os.path.join(ROOT, 'roms', GAME, 'prog68k.bin')
TILES = os.path.join(ROOT, 'sh_src', 'tiles.bin')
SCENE_TABLE, SCENES, TILES_N = 0x1CE2, 5, 20480

def unpack(rom, base):
    hi = bytearray(); p = base
    while len(hi) < TILES_N:
        cnt, val = rom[p], rom[p + 1]; p += 2; hi += bytes([val]) * (cnt + 1)
    lo = bytearray()
    while len(lo) < TILES_N:
        b = rom[p]; p += 1
        if b: lo.append(b)
        else:
            n = rom[p]; p += 1; lo += bytes(n + 1)   # zero run = n+1 (LOOP29 243)
    return [(hi[i] << 8) | lo[i] for i in range(TILES_N)]

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--stats', action='store_true')
    a = ap.parse_args()
    rom = open(ROM, 'rb').read()
    if not os.path.exists(TILES):
        sys.exit('sh_src/tiles.bin missing -- run tools/gen_tiles.py first')
    tiles = open(TILES, 'rb').read()
    def kind(idx):
        o = idx * 64
        if o + 64 > len(tiles): return 2
        art = tiles[o:o + 64]
        if not any(art): return 0
        return 1 if 0 not in art else 2
    out = bytearray(); rows = []
    for s in range(SCENES):
        o = SCENE_TABLE + 6 * s
        W = unpack(rom, int.from_bytes(rom[o + 2:o + 6], 'big'))
        m = bytearray(TILES_N // 4)
        c = {'fg': [0, 0, 0], 'bg': [0, 0, 0]}
        for i, w in enumerate(W):
            k = 0
            if w & 0x8000:
                k = kind(w & 0x1FFF)
            m[i >> 2] |= k << ((3 - (i & 3)) * 2)
            if w & 0x8000:
                c['fg' if i < 5 * 2048 else 'bg'][k] += 1
        out += m; rows.append((s, c))
    print('scene  plane   cat1   no-hole(blank)  suppress-all  per-pixel')
    for s, c in rows:
        for pl in ('fg', 'bg'):
            n = sum(c[pl]); print(f"  {s}     {pl}   {n:5d}      {c[pl][0]:5d}          {c[pl][1]:5d}       {c[pl][2]:5d}")
    if a.stats: return
    open(os.path.join(ROOT, 'sh_src', 'cat1hole.bin'), 'wb').write(out)
    with open(os.path.join(ROOT, 'sh_src', 'cat1hole.h'), 'w') as fh:
        fh.write('/* generated by tools/bake_cat1hole.py (LOOP-DECOMPILE 65/106):\n'
                 ' * two bits per cell, 0 no hole / 1 suppress whole cell / 2 per\n'
                 ' * pixel. Cell n of scene s: byte s*5120 + n/4, field (3-n%4)*2.\n'
                 ' * Apply on FOREGROUND pages only (0-4). */\n')
        fh.write('#define CAT1HOLE_BYTES_PER_SCENE %d\n' % (TILES_N // 4))
        fh.write('#define CAT1HOLE_GET(map, n) (((map)[(n) >> 2] >> ((3 - ((n) & 3)) * 2)) & 3)\n')
        fh.write('static const unsigned short cat1hole_fg_all[%d] = { %s };  /* suppress-all cells, FG pages */\n'
                 % (SCENES, ', '.join(str(c['fg'][1]) for _, c in rows)))
        fh.write('static const unsigned short cat1hole_fg_pix[%d] = { %s };  /* per-pixel cells, FG pages */\n'
                 % (SCENES, ', '.join(str(c['fg'][2]) for _, c in rows)))
    print('wrote sh_src/cat1hole.bin and sh_src/cat1hole.h')

if __name__ == '__main__':
    main()
