#!/usr/bin/env python3
"""Bake the per-scene CAT1 (tile priority) bitmaps out of the arcade rom.

    tools/bake_cat1map.py            # regenerate outputs
    tools/bake_cat1map.py --stats    # print the table only

Category 1 is bit 15 of a System 16 tile word — the PRIORITY FLAG
(`srcref/jtcores/cores/s16b/doc/s16b.txt` section 6). It is not a runtime
decision: the unpacker's high-byte pass (0x16BE) writes it from a
run-length stream in the rom, and the decode here reproduces live tile RAM
BYTE FOR BYTE, 20480 of 20480, at frames 1200 and 2400 alike
(docs/log/LOOP-DECOMPILE.md 31).

So promotion can be decided at bake time and never re-examined.

Emits:
  sh_src/cat1map.bin   5 scenes x 2560 bytes, one BIT per tile, MSB first,
                       tile n of scene s at byte s*2560 + n/8, bit 7-(n%8)
  sh_src/cat1map.h     offsets, counts and the per-scene share
"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = os.environ.get('GAME', 'altbeast')
ROM = os.path.join(ROOT, 'roms', GAME, 'prog68k.bin')

SCENE_TABLE = 0x1CE2        # 6 bytes per entry: word -> 0xFFF095, long -> data
SCENES = 5                  # entries 5-7 run into the copyright string
TILES = 20480               # the pass writes 0x5000 words
BYTES_PER_SCENE = TILES // 8


def hi_pass(rom, src, limit=TILES):
    """Replay 0x16BE: (count, value) pairs, value written count+1 times."""
    out = bytearray()
    p = src
    while len(out) < limit and p + 1 < len(rom):
        out.extend(bytes([rom[p + 1]]) * (rom[p] + 1))
        p += 2
    return out[:limit]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--stats', action='store_true')
    a = ap.parse_args()

    with open(ROM, 'rb') as fh:
        rom = fh.read()

    maps, stats = [], []
    for s in range(SCENES):
        o = SCENE_TABLE + 6 * s
        ptr = int.from_bytes(rom[o + 2:o + 6], 'big')
        hi = hi_pass(rom, ptr)
        if len(hi) != TILES:
            sys.exit('scene %d: decoded %d tiles, expected %d' % (s, len(hi), TILES))
        bits = bytearray(BYTES_PER_SCENE)
        n = 0
        for i, b in enumerate(hi):
            if b & 0x80:
                bits[i >> 3] |= 0x80 >> (i & 7)
                n += 1
        maps.append(bits)
        stats.append((s, ptr, n))

    print('scene  data ptr   cat1 tiles   share')
    for s, ptr, n in stats:
        print('  %d    0x%05X     %6d    %5.1f%%' % (s, ptr, n, 100.0 * n / TILES))
    print('total %d bytes' % (SCENES * BYTES_PER_SCENE))
    if a.stats:
        return

    with open(os.path.join(ROOT, 'sh_src', 'cat1map.bin'), 'wb') as fh:
        for m in maps:
            fh.write(m)
    with open(os.path.join(ROOT, 'sh_src', 'cat1map.h'), 'w') as fh:
        fh.write('/* generated by tools/bake_cat1map.py — per-scene tile\n'
                 ' * priority (CAT1) bitmaps. One bit per tile, MSB first:\n'
                 ' * scene s tile n = cat1map[s*%d + (n>>3)] & (0x80>>(n&7)).\n'
                 ' * Static per scene; see docs/log/LOOP-DECOMPILE.md 31. */\n'
                 % BYTES_PER_SCENE)
        fh.write('#define CAT1_SCENES %d\n#define CAT1_TILES %d\n'
                 '#define CAT1_BYTES_PER_SCENE %d\n'
                 % (SCENES, TILES, BYTES_PER_SCENE))
        fh.write('static const unsigned short cat1_counts[CAT1_SCENES] = { %s };\n'
                 % ', '.join(str(n) for _, _, n in stats))
    print('wrote sh_src/cat1map.bin and sh_src/cat1map.h')


if __name__ == '__main__':
    main()
