#!/usr/bin/env python3
"""Full-length oracle music sweep -> LZSS-compressed render_music.h. KIT.

Segments a tools/music_sweep.lua log (the arcade ORACLE playing each
music command full-length), transcodes each via opm2opn, LZSS-compresses
(tools/lzss.py), and emits sndtest/md/render_music.h: compressed track
arrays + a {cmd -> ptr,len} lookup the router stream-decompresses
(docs/sound/SOUND_DRIVER.md). Full songs fit the 512KB 68K window via ~4x LZSS.

  build_music.py MUSIC_LOG --out sndtest/md/render_music.h [--secs 60]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from soundmap_build import parse_log, transcode                # noqa: E402
from lzss import compress, decompress                          # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("log")
    ap.add_argument("--secs", type=float, default=60.0)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    segs = parse_log(args.log)
    tracks = []
    for seg in segs:
        cmd = seg["cmd"]
        raw = bytes(transcode(seg, loop=True, secs=args.secs))
        comp = compress(raw)
        assert decompress(comp) == raw, f"lzss roundtrip failed cmd {cmd:#x}"
        tracks.append((cmd, comp, len(raw)))
        print(f"  0x{cmd:02X}: {len(raw):6d}B raw -> {len(comp):6d}B lzss "
              f"({len(raw)/len(comp):.2f}x)", file=sys.stderr)

    with open(args.out, "w") as f:
        f.write("/* AUTO-GENERATED by tools/build_music.py — every music\n"
                " * command captured full-length from the arcade oracle\n"
                " * (tools/music_sweep.lua), transcoded, LZSS-compressed.\n"
                " * The router stream-decompresses into the Z80 ring\n"
                " * (docs/sound/SOUND_DRIVER.md). Do not edit. */\n"
                "#include <stdint.h>\n\n")
        # emit the intro/loop struct the player expects; loop-whole means
        # intro == loop == the whole compressed track (pre-VGZ behaviour).
        for cmd, comp, rawlen in tracks:
            f.write(f"/* cmd 0x{cmd:02X}: {rawlen} bytes uncompressed */\n")
            f.write(f"static const uint8_t rtrk_{cmd:02X}[{len(comp)}] = {{\n")
            for o in range(0, len(comp), 16):
                f.write("\t" + ",".join("0x%02X" % b for b in comp[o:o + 16]) + ",\n")
            f.write("};\n")
        f.write("\nstruct rtrk { uint8_t cmd; const uint8_t *intro;"
                " uint32_t intro_len; const uint8_t *loop; uint32_t loop_len; };\n")
        f.write(f"static const struct rtrk render_music[{len(tracks)}] = {{\n")
        for cmd, comp, rawlen in tracks:
            f.write(f"\t{{ 0x{cmd:02X}, rtrk_{cmd:02X}, {len(comp)}, "
                    f"rtrk_{cmd:02X}, {len(comp)} }},\n")
        f.write("};\n")
        f.write("#define RENDER_MUSIC_COUNT %d\n" % len(tracks))
    tot = sum(len(c) for _, c, _ in tracks)
    print(f"render_music.h: {len(tracks)} tracks, {tot} bytes compressed "
          f"({tot/1024:.0f}KB — fits the 512KB window)", file=sys.stderr)


if __name__ == "__main__":
    main()
