#!/usr/bin/env python3
"""Generate the P3 streaming test track (docs/sound/SOUND.md P3).

Emits sndtest/md/test_track.h: a stream in the Z80 player's opcode
format (wait n / $F0 reg val / $F2 psg) playing a four-note FM
arpeggio on YM2612 ch1 with a PSG square bass under it. The 68K
feeder wraps the source forever, so the stream has NO $FF terminator
— the loop is the wrap. Sized well past the 4KB Z80 ring so the
streaming path (block feed, wrap, starve-stall) is actually exercised.

RULES the stream obeys (and the P4 transcoder must too):
- never writes YM reg $27 (Timer A is the player's clock)
- opens with full patch + PSG silence so a restart is deterministic
"""
import sys

out = []


def ym(reg, val):
    out.extend([0xF0, reg & 0xFF, val & 0xFF])


def psg(val):
    out.extend([0xF2, val & 0xFF])


def wait_ms(n):
    while n > 127:
        out.append(127)
        n -= 127
    if n:
        out.append(n)


# ch1 patch. v1 reused the P0 "sting" voice and CLIPPED HARD on ares
# (Mike, 2026-09-01): algorithm 7 + feedback 5 = four hot carriers
# summed — a voice 32x-builder abandoned before it was ever validated
# audibly. v2 is a clean bell: ALGORITHM 4 (two 2-op stacks, carriers
# S2+S4 at modest TL), feedback 2, no AMS/FMS. Register slot order is
# the YM2612 scramble: +0,+4,+8,+C = S1,S3,S2,S4 — so the CARRIER TLs
# are 0x48/0x4C and the modulators 0x40/0x44.
PATCH = [
    (0x22, 0x00), (0x2B, 0x00),
    (0x30, 0x02), (0x34, 0x02), (0x38, 0x01), (0x3C, 0x02),  # DT/MUL
    (0x40, 0x2E), (0x44, 0x32), (0x48, 0x18), (0x4C, 0x1A),  # TL
    (0x50, 0x1F), (0x54, 0x1F), (0x58, 0x1F), (0x5C, 0x1F),  # KS/AR
    (0x60, 0x08), (0x64, 0x08), (0x68, 0x06), (0x6C, 0x06),  # AM/DR
    (0x70, 0x00), (0x74, 0x00), (0x78, 0x00), (0x7C, 0x00),  # SR
    (0x80, 0x28), (0x84, 0x28), (0x88, 0x28), (0x8C, 0x28),  # SL/RR
    (0x90, 0x00), (0x94, 0x00), (0x98, 0x00), (0x9C, 0x00),  # SSG-EG off
    (0xB0, 0x14),                                            # FB2 ALG4
    (0xB4, 0xC0),                                            # L+R, no LFO
]

# F-numbers (block-4 base octave): C E G C'
FNUM = {"C4": 644, "E4": 810, "G4": 964, "C5": 1288}


def note_on(name, block=4):
    fn = FNUM[name]
    if fn > 0x7FF:
        fn >>= 1
        block += 1
    ym(0x28, 0x00)                      # key off ch1
    ym(0xA4, ((block & 7) << 3) | (fn >> 8))
    ym(0xA0, fn & 0xFF)
    ym(0x28, 0xF0)                      # key on ch1, all operators


def psg_tone(freq, vol):
    div = int(3579545 / (32 * freq))
    psg(0x80 | (div & 0x0F))            # ch0 tone latch, low 4
    psg((div >> 4) & 0x3F)              # data, high 6
    psg(0x90 | (vol & 0x0F))            # ch0 attenuation


# --- stream start: silence PSG, upload patch --------------------------
for v in (0x9F, 0xBF, 0xDF, 0xFF):
    psg(v)
for reg, val in PATCH:
    ym(reg, val)
wait_ms(10)

# --- body: 64 one-second phrases (~6KB, > the 4KB ring) ---------------
SEQ = ["C4", "E4", "G4", "C5"]
BASS = [131, 165, 196, 131]             # C3 E3 G3 C3
# PSG attenuation 9/11 (-18/-22 dB): the SN76489 at att 4 swamps the
# YM mix — part of the v1 "clipping" report.
for phrase in range(64):
    for i, n in enumerate(SEQ):
        psg_tone(BASS[i], 9 if (phrase & 1) == 0 else 11)
        note_on(n)
        wait_ms(220)
        psg(0x9F)                       # bass off
        wait_ms(30)

path = sys.argv[1] if len(sys.argv) > 1 else "sndtest/md/test_track.h"
with open(path, "w") as f:
    f.write("/* AUTO-GENERATED by tools/mus_testgen.py — do not edit. */\n"
            "#include <stdint.h>\n\n")
    f.write("#define TEST_TRACK_LEN %d\n\n" % len(out))
    f.write("static const uint8_t test_track[TEST_TRACK_LEN] = {\n")
    for off in range(0, len(out), 16):
        f.write("\t" + ",".join("0x%02X" % b for b in out[off:off + 16]) + ",\n")
    f.write("};\n")
print("test_track.h: %d bytes (%d phrases)" % (len(out), 64))
