#!/usr/bin/env python3
"""Render ALL S16B music commands to one player-track header. KIT.

Runs the real driver (tools/snd_render.py, with the master-volume idle
fix — docs/sound/SOUND_DRIVER.md "THE FADE LAW") for each music command, transcodes
via opm2opn, and emits render_music.h: the track arrays plus a
{cmd -> (ptr,len)} lookup the router uses so EVERY music command plays a
faithful, non-fading cut (not the isolation-sweep trk_XX).

  render_music.py PROG_ROM --samples s1 s2 --out sndtest/md/render_music.h \
      [--cmds 90 91 ... ] [--ticks 1800]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from snd_render import render                                # noqa: E402
from soundmap_build import transcode                         # noqa: E402

# Altered Beast music commands (SND_MUSIC in sndmap_data.h)
DEFAULT_CMDS = [0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97,
                0xB1, 0xB2, 0xD3]


def render_cmd(prog, samples, cmd, ticks, ym_clock):
    board = render(prog, samples, cmd, ticks, ym_clock)
    ta = board.ta or 1
    period_s = 64 * (1024 - ta) / ym_clock
    denom = 64 * (1024 - ta)
    seg = {"cmd": cmd, "t0": 0.0, "t1": None,
           "ym": [], "pc": [], "pd": [], "shadow": [0] * 256}
    addr = 0
    for cyc, kind, val in board.events:
        if kind == "Y0":
            addr = val
        elif kind == "Y1":
            seg["ym"].append(((cyc / denom) * period_s, addr, val))
        elif kind == "PD":
            seg["pd"].append(((cyc / denom) * period_s, val))
    return transcode(seg, loop=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("prog")
    ap.add_argument("--samples", nargs="*", default=[])
    ap.add_argument("--cmds", nargs="*", default=None,
                    help="hex command bytes; default = all AB music cmds")
    ap.add_argument("--ticks", type=int, default=1800)
    ap.add_argument("--ym-clock", type=int, default=4000000)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    prog = open(args.prog, "rb").read()
    samples = [open(s, "rb").read() for s in args.samples]
    cmds = [int(c, 16) for c in args.cmds] if args.cmds else DEFAULT_CMDS

    tracks = []
    for cmd in cmds:
        data = render_cmd(prog, samples, cmd, args.ticks, args.ym_clock)
        tracks.append((cmd, data))
        print(f"  cmd 0x{cmd:02X}: {len(data)} bytes", file=sys.stderr)

    with open(args.out, "w") as f:
        f.write("/* AUTO-GENERATED by tools/render_music.py — every music\n"
                " * command rendered by executing the real S16B driver\n"
                " * (docs/sound/SOUND_DRIVER.md), full volume, non-fading. Do not edit. */\n"
                "#include <stdint.h>\n\n")
        for cmd, data in tracks:
            f.write(f"static const uint8_t rtrk_{cmd:02X}[{len(data)}] = {{\n")
            for o in range(0, len(data), 16):
                f.write("\t" + ",".join("0x%02X" % b for b in data[o:o + 16]) + ",\n")
            f.write("};\n")
        f.write("\nstruct rtrk { uint8_t cmd; const uint8_t *p; uint32_t len; };\n")
        f.write(f"static const struct rtrk render_music[{len(tracks)}] = {{\n")
        for cmd, data in tracks:
            f.write(f"\t{{ 0x{cmd:02X}, rtrk_{cmd:02X}, {len(data)} }},\n")
        f.write("};\n")
        f.write("#define RENDER_MUSIC_COUNT %d\n" % len(tracks))
    total = sum(len(d) for _, d in tracks)
    print(f"render_music.h: {len(tracks)} tracks, {total} bytes total",
          file=sys.stderr)


if __name__ == "__main__":
    main()
