#!/usr/bin/env python3
"""Render one S16B music command to a Z80-player track header. KIT.

Runs the real sound driver (tools/snd_render.py), transcodes the captured
YM2151 stream to YM2612 player opcodes with the SAME mapping the rest of
the pipeline uses (tools/soundmap_build.transcode), and emits a C array
the sndtest ROM (or the shipping rom) can play. This is the faithful
music path — the driver's per-note envelope refresh is in the stream, so
notes sustain (SOUND_DRIVER.md), unlike the isolation-sweep tracks.

  render_track.py PROG_ROM --cmd 0x94 --ticks 1800 --samples s1 s2 \
      --name render_track --out sndtest/md/render_track.h
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from snd_render import render                                # noqa: E402
from soundmap_build import transcode                         # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("prog")
    ap.add_argument("--cmd", type=lambda x: int(x, 0), default=0x94)
    ap.add_argument("--ticks", type=int, default=1800)
    ap.add_argument("--samples", nargs="*", default=[])
    ap.add_argument("--ym-clock", type=int, default=4000000)
    ap.add_argument("--name", default="render_track")
    ap.add_argument("--no-loop", action="store_true")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    prog = open(args.prog, "rb").read()
    samples = [open(s, "rb").read() for s in args.samples]
    board = render(prog, samples, args.cmd, args.ticks, args.ym_clock)

    # tick period (Timer A) -> seconds, for the transcoder's timeline
    ta = board.ta or 1
    period_s = 64 * (1024 - ta) / args.ym_clock
    denom = 64 * (1024 - ta)
    seg = {"cmd": args.cmd, "t0": 0.0, "t1": None,
           "ym": [], "pc": [], "pd": [], "shadow": [0] * 256}
    for cyc, kind, val in board.events:
        if kind == "Y0":
            addr = val
        elif kind == "Y1":
            t = (cyc / denom) * period_s
            seg["ym"].append((t, addr, val))
        elif kind == "PD":
            seg["pd"].append(((cyc / denom) * period_s, val))

    data = transcode(seg, loop=not args.no_loop)
    up = args.name.upper()
    with open(args.out, "w") as f:
        f.write(f"/* AUTO-GENERATED by tools/render_track.py — cmd 0x{args.cmd:02X}\n"
                f" * rendered by executing the real S16B sound driver\n"
                f" * (SOUND_DRIVER.md). {len(data)} bytes, "
                f"{'loop' if not args.no_loop else 'one-shot'}. Do not edit. */\n"
                f"#define {up}_LEN {len(data)}\n"
                f"static const uint8_t {args.name}[{up}_LEN] = {{\n")
        for off in range(0, len(data), 16):
            f.write("\t" + ",".join("0x%02X" % b for b in data[off:off + 16]) + ",\n")
        f.write("};\n")
    print(f"{args.name}: {len(data)} bytes -> {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
