#!/usr/bin/env python3
"""Sound-post census: which 68K site posts which sound command.

The game's only sound entry point is 0x3352 (LOOP-DECOMPILE 32: enqueue
d0.b with de-dup, drained to the MCU mailbox 0xFFF0C4). This walks every
call/jump to it in docs/audit/code_stream.txt, recovers the command byte
from the immediate that loads d0 just before it, names the enclosing
function from docs/audit/function_map2.md, and joins the sweep-derived
class from sndtest/md/sndmap_data.h (soundmap_build.py's output).

Usage: tools/sound_posts.py [--md docs/audit/sound_posts.md]
"""
import re, sys, argparse
from collections import defaultdict

STREAM = 'docs/audit/code_stream.txt'
FMAP   = 'docs/audit/function_map2.md'
SNDMAP = 'sndtest/md/sndmap_data.h'
ENTRY  = '0x3352'

def load_rows():
    return [l.rstrip('\n').split('\t') for l in open(STREAM)]

def load_fmap():
    fm = []
    for l in open(FMAP):
        m = re.match(r'\|\s*0x([0-9A-Fa-f]+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*([^|]*)\|', l)
        if m:
            fm.append((int(m.group(1), 16), int(m.group(2)), m.group(4).strip()))
    return fm

def load_sndmap():
    cls = {}
    for l in open(SNDMAP):
        m = re.search(r'\{\s*(\d+),\s*(\d+),\s*(0x[0-9A-Fa-f]+)\s*\},\s*/\*\s*0x([0-9A-Fa-f]{2})\s*(.*?)\s*\*/', l)
        if m:
            cls[int(m.group(4), 16)] = (int(m.group(1)), int(m.group(2)), int(m.group(3), 16), m.group(5))
    return cls

def census():
    rows = load_rows(); fm = load_fmap()
    def func(a):
        f = [x for x in fm if x[0] <= a < x[0] + x[1]]
        return (f"0x{f[0][0]:05X}", f[0][2]) if f else ('?', '?')
    sites = []
    for i, r in enumerate(rows):
        if r[2] in ('jsr', 'jmp', 'bsrw', 'bsrs', 'braw', 'bras') and r[3] == ENTRY:
            val, how = None, 'computed'
            for j in range(i - 1, max(i - 4, 0), -1):
                m = rows[j]; ops = m[3].split(',')
                if len(ops) == 2 and ops[1] == '%d0':
                    if ops[0].startswith('#'):
                        val, how = int(ops[0][1:]) & 0xff, m[2]
                    else:
                        how = f"{m[2]} {ops[0]}"
                    break
                if '%d0' in m[3]:
                    how = f"{m[2]} {m[3]}"; break
            a = int(r[0], 16)
            sites.append((a, r[2], val, how) + func(a))
    return sites

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--md'); args = ap.parse_args()
    sites = census(); cls = load_sndmap()
    by = defaultdict(list)
    for s in sites: by[s[2]].append(s)
    out = []
    out.append("# Sound-post census: which 68K site posts which command\n")
    out.append("Generated by `tools/sound_posts.py` from `docs/audit/code_stream.txt`, "
               "`docs/audit/function_map2.md` and `sndtest/md/sndmap_data.h`. "
               "Entry point 0x3352 (LOOP-DECOMPILE 32). The class column is the sound "
               "thread's sweep classification of the command byte in isolation; the "
               "function column is where the GAME posts it.\n")
    n_imm = sum(1 for s in sites if s[2] is not None)
    out.append(f"Sites: {len(sites)}, with an immediate command byte: {n_imm}, "
               f"distinct commands: {len([k for k in by if k is not None])}.\n")
    out.append("| cmd | class (sweep) | sites | posted from |")
    out.append("|---|---|---|---|")
    for v in sorted(by, key=lambda x: (x is None, x or 0)):
        lst = by[v]
        if v is None:
            tag, c = 'computed', '-'
        else:
            tag = f"0x{v:02X}"
            c = cls.get(v)
            c = (f"type {c[0]} idx {c[1]} sp 0x{c[2]:02X} {c[3]}".strip()) if c else 'not in sndmap'
        funcs = defaultdict(int)
        for s in lst: funcs[(s[4], s[5])] += 1
        where = '; '.join(f"{f[0]} {f[1]}" + (f" x{k}" if k > 1 else '') for f, k in sorted(funcs.items()))
        out.append(f"| {tag} | {c} | {len(lst)} | {where} |")
    out.append("\n## Every site\n")
    out.append("| site | op | cmd | d0 loaded by | function |")
    out.append("|---|---|---|---|---|")
    for a, op, v, how, fa, fn in sorted(sites):
        out.append(f"| 0x{a:05X} | {op} | {'0x%02X' % v if v is not None else '-'} | {how} | {fa} {fn} |")
    text = '\n'.join(out) + '\n'
    if args.md:
        open(args.md, 'w').write(text); print(f"wrote {args.md}: {len(sites)} sites")
    else:
        sys.stdout.write(text)

if __name__ == '__main__':
    main()
