#!/usr/bin/env python3
"""Bake a directory of WAVs into the sndtest speech bank (docs/sound/SOUND.md P1).

Reads the unique utterances from tools/upd7759_decode.py's output dir
(manifest.json + utt_*.wav), resamples every WAV to the mixer rate,
IMA-ADPCM encodes them (4 bits/sample, headerless), and emits one
speech_bank.c / speech_bank.h pair holding the whole bank as a table:

    struct speech_sample { const uint8_t *data; uint32_t nibbles; };
    extern const struct speech_sample speech_bank[];

Nibble packing matches sndtest/sh/sound.c's decoder: EVEN sample = LOW
nibble. The encoder mirrors the decoder's reconstruction exactly
(delta = step>>3 + conditional step/step>>1/step>>2 terms) so encode
and decode share one arithmetic — the 32x-builder adpcm_bake.py rule.

Usage: speech_bake.py SPEECH_DIR OUT_C [--rate 16000]
"""
import argparse
import json
import os
import wave

STEP_TABLE = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31,
    34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143,
    157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544,
    598, 658, 724, 796, 876, 963, 1060, 1166, 1282, 1411, 1552, 1707,
    1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871,
    5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899,
    15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794, 32767,
]
INDEX_TABLE = [-1, -1, -1, -1, 2, 4, 6, 8, -1, -1, -1, -1, 2, 4, 6, 8]


def ima_encode(samples):
    pred, idx = 0, 0
    nibbles = []
    for s in samples:
        step = STEP_TABLE[idx]
        diff = s - pred
        nib = 0
        if diff < 0:
            nib = 8
            diff = -diff
        if diff >= step:
            nib |= 4
            diff -= step
        if diff >= step >> 1:
            nib |= 2
            diff -= step >> 1
        if diff >= step >> 2:
            nib |= 1
        # reconstruct exactly like the SH-2 decoder
        delta = step >> 3
        if nib & 4:
            delta += step
        if nib & 2:
            delta += step >> 1
        if nib & 1:
            delta += step >> 2
        pred += -delta if nib & 8 else delta
        pred = max(-32768, min(32767, pred))
        idx = max(0, min(88, idx + INDEX_TABLE[nib]))
        nibbles.append(nib)
    return nibbles


def load_wav_16k(path, rate):
    # pure python (audioop left the stdlib in 3.13): 16-bit only, mono
    # by channel-average, nearest-sample resample when rates differ
    # (upd7759_decode.py output is already mono 16-bit at the mix rate).
    with wave.open(path, "rb") as w:
        assert w.getsampwidth() == 2, "%s: need 16-bit PCM" % path
        nch = w.getnchannels()
        data = w.readframes(w.getnframes())
        raw = [int.from_bytes(data[i:i + 2], "little", signed=True)
               for i in range(0, len(data) - 1, 2)]
        if nch > 1:
            raw = [sum(raw[i:i + nch]) // nch for i in range(0, len(raw), nch)]
        src = w.getframerate()
    if src == rate:
        return raw
    out_n = len(raw) * rate // src
    return [raw[i * src // rate] for i in range(out_n)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("speech_dir")
    ap.add_argument("out_c")
    ap.add_argument("--rate", type=int, default=16000)
    args = ap.parse_args()

    manifest = json.load(open(os.path.join(args.speech_dir, "manifest.json")))
    uniq = [e for e in manifest if "wav" in e]

    banks = []
    for e in uniq:
        samples = load_wav_16k(os.path.join(args.speech_dir, e["wav"]), args.rate)
        nibs = ima_encode(samples)
        if len(nibs) & 1:
            nibs.append(0)
        packed = bytes((nibs[i] | (nibs[i + 1] << 4))
                       for i in range(0, len(nibs), 2))
        banks.append((e, packed, len(nibs)))

    out_h = os.path.splitext(args.out_c)[0] + ".h"
    guard = "SPEECH_BANK_H"
    with open(out_h, "w") as h:
        h.write("/* AUTO-GENERATED by tools/speech_bake.py — do not edit.\n"
                " * IMA ADPCM @ %d Hz, even sample = LOW nibble. */\n"
                "#ifndef %s\n#define %s\n\n#include <stdint.h>\n\n"
                % (args.rate, guard, guard))
        h.write("struct speech_sample { const uint8_t *data; uint32_t nibbles; };\n")
        h.write("#define SPEECH_BANK_COUNT %d\n" % len(banks))
        h.write("extern const struct speech_sample speech_bank[SPEECH_BANK_COUNT];\n")
        h.write("\n#endif\n")

    with open(args.out_c, "w") as c:
        c.write("/* AUTO-GENERATED by tools/speech_bake.py — do not edit. */\n")
        c.write('#include "%s"\n\n' % os.path.basename(out_h))
        for i, (e, packed, nnib) in enumerate(banks):
            c.write("/* bank %d: %s %dms cmds%s */\n"
                    % (i, e["wav"], e["ms"], e["cmds_before"]))
            c.write("static const uint8_t bank_%02d[] "
                    "__attribute__((aligned(4))) = {\n" % i)
            for off in range(0, len(packed), 16):
                c.write("\t" + ",".join("0x%02X" % b
                                        for b in packed[off:off + 16]) + ",\n")
            c.write("};\n")
        c.write("\nconst struct speech_sample speech_bank[SPEECH_BANK_COUNT] = {\n")
        for i, (e, packed, nnib) in enumerate(banks):
            c.write("\t{ bank_%02d, %d },\n" % (i, nnib))
        c.write("};\n")

    total = sum(len(p) for _, p, _ in banks)
    print("%d samples, %d KB ADPCM -> %s" % (len(banks), total // 1024, args.out_c))


if __name__ == "__main__":
    main()
