#!/usr/bin/env python3
"""Package the Z80 player blob for the 68K (docs/sound/SOUND.md P3).

Reads player.bin (wla-z80 output: an 8KB image that executes from Z80
RAM) and emits a C header with the code bytes plus the mailbox/ring
contract addresses parsed straight out of player.asm's .DEFINE lines —
the asm stays the single source of truth (the 32x-builder
gen_z80_game.py rule: a drifted hand-copied constant is a week of
debugging).

Upload length = last nonzero byte of the image, rounded up to even;
the tail is .EMPTYFILL zeros over the ring/mailbox space the 68K owns.

Usage: z80_pack.py player.asm player.bin out.h
"""
import re
import sys

asm_path, bin_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

WANT = ("RD_BLK", "WR_BLK", "MSTAT", "MGO", "RING", "STACK")
defines = {}
for line in open(asm_path):
    m = re.match(r"\s*\.DEFINE\s+(\w+)\s+\$([0-9A-Fa-f]+)", line)
    if m and m.group(1) in WANT:
        defines[m.group(1)] = int(m.group(2), 16)
missing = [w for w in WANT if w not in defines]
if missing:
    sys.exit("z80_pack: missing .DEFINEs in %s: %s" % (asm_path, missing))

blob = open(bin_path, "rb").read()
end = len(blob)
while end > 0 and blob[end - 1] == 0:
    end -= 1
end += end & 1
code = blob[:end]
if end > defines["STACK"]:
    sys.exit("z80_pack: code (%d bytes) reaches the stack/mailbox area "
             "($%04X)" % (end, defines["STACK"]))

with open(out_path, "w") as f:
    f.write("/* AUTO-GENERATED by tools/z80_pack.py — do not edit.\n"
            " * Z80 streaming music player; contract addresses parsed\n"
            " * from player.asm. */\n#include <stdint.h>\n\n")
    for k in WANT:
        f.write("#define ZP_%s 0x%04X\n" % (k, defines[k]))
    f.write("#define Z80_PLAYER_LEN %d\n\n" % len(code))
    f.write("static const uint8_t z80_player[Z80_PLAYER_LEN] = {\n")
    for off in range(0, len(code), 16):
        f.write("\t" + ",".join("0x%02X" % b for b in code[off:off + 16]) + ",\n")
    f.write("};\n")

print("z80_player.h: %d code bytes, ring at $%04X" % (len(code), defines["RING"]))
